// Generated by scripts/build-mv3-worker.mjs. Do not edit by hand.
(() => {
"use strict";
/* generated by jison-lex 0.3.4 */
var llexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {"moduleType":"commonjs","moduleName":"llexer"},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0: if(this.opt_t) console.log(`comment: <${yy_.yytext}>`); 
break;
case 1: if(this.opt_t) console.log(`comment: <${yy_.yytext}>`); 
break;
case 2: this.yylval = ''; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 3:
  this.yylval = Number(yy_.yytext);
  if(this.opt_t) console.log(`<scientific:${yy_.yytext}>`);
  return 'number';

break;
case 4:
  this.yylval = parseInt(yy_.yytext, 8);
  if(this.opt_t) console.log(`<octal:${yy_.yytext}>`);
  return 'number';

break;
case 5:
  this.yylval = Number(yy_.yytext);
  if(this.opt_t) console.log(`<float:${yy_.yytext}>`);
  return 'number';

break;
case 6:
  this.yylval = parseInt(yy_.yytext, 10);
  if(this.opt_t) console.log(`<decimal:${yy_.yytext}>`);
  return 'number';

break;
case 7: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 8: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 9: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 10: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 11: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 12: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 13: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 14: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 15: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 16: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 17: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 18: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 19: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 20: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 21: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 22: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 23: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 24: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 25: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 26: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 27: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 28: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 29: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 30: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 31: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 32: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 33: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 34: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 35: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 36: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 37: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 38: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 39: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 40: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 41: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 42: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 43: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 44: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 45: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 46: this.yylval = yy_.yytext; if(this.opt_t) console.log(`${yy_.yytext}`); return yy_.yytext;  
break;
case 47: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 48: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 49: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 50: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 51: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 52: this.yylval = yy_.yytext; if(this.opt_t) console.log(`<${yy_.yytext}>`); return yy_.yytext; 
break;
case 53:
  this.yylval = yy_.yytext;
  if(this.opt_t) console.log(`<ident:${yy_.yytext}>`);
  return 'ident';

break;
case 54:
  try{
    this.yylval = JSON.parse(yy_.yytext)
  }
  catch(err){
    throw `cannot parse <${yy_.yytext}>`;
  }
  if(this.opt_t) console.log(`<string:${JSON.stringify(this.yylval)}>`);
  return 'string';

break;
case 55:
  let i = 1, acc = '"';
  while(i < yy_.yytext.length - 1){
    if(yy_.yytext[i] == '\\' && i + 1 < yy_.yytext.length - 1){
      if(yy_.yytext[i + 1] == "'") acc += "'";
      else acc += yy_.yytext.substr(i, 2);
      i += 1;
    }
    else acc += yy_.yytext[i];
    i += 1;
  }
  acc += '"';
  this.yylval = JSON.parse(acc);
  if(this.opt_t) console.log(`<string:${JSON.stringify(this.yylval)}>`);
  return 'string';

break;
case 56:
break;
case 57: return 'nl'; 
break;
case 58: this.yylval = yy_.yytext; return 'EOF'; 
break;
case 59: throw `Error at line ${yy_.yylloc.first_line}: bad character ${yy_.yytext}`; 
break;
}
},
rules: [/^(?:\/\*(\*[^/]|[^*])*\*\/)/,/^(?:\/\/[^\n]*)/,/^(?:(,|;|:|\(|\)|\[|\]|\{|\}))/,/^(?:[+-]?((0|[1-9]+[0-9]*)|((0|([1-9])([0-9])*)\.(([0-9])*([1-9])|)))[Ee][+-]?(0|[1-9]+[0-9]*))/,/^(?:[+-]?(0[0-7]+))/,/^(?:[+-]?((0|([1-9])([0-9])*)\.(([0-9])*([1-9])|)))/,/^(?:(0|[1-9]+[0-9]*))/,/^(?:>>>=)/,/^(?:>>>)/,/^(?:<<=)/,/^(?:>>=)/,/^(?:===)/,/^(?:!==)/,/^(?:&&=)/,/^(?:\|\|=)/,/^(?:\?\?=)/,/^(?:==)/,/^(?:!=)/,/^(?:<=)/,/^(?:>=)/,/^(?:=>)/,/^(?:\*\*)/,/^(?:<<)/,/^(?:>>)/,/^(?:&&)/,/^(?:\|\|)/,/^(?:\+\+)/,/^(?:--)/,/^(?:\+=)/,/^(?:-=)/,/^(?:\*=)/,/^(?:\/=)/,/^(?:&=)/,/^(?:\^=)/,/^(?:\|=)/,/^(?:%=)/,/^(?:\?\?)/,/^(?:\?\.)/,/^(?:\+)/,/^(?:-)/,/^(?:\*)/,/^(?:\/)/,/^(?:%)/,/^(?:<)/,/^(?:>)/,/^(?:!)/,/^(?:~)/,/^(?:=)/,/^(?:\?)/,/^(?:\.)/,/^(?:&)/,/^(?:\^)/,/^(?:\|)/,/^(?:([_$a-zA-Z])(([_$a-zA-Z])|([0-9]))*)/,/^(?:"(\\"|[^\n"])*")/,/^(?:'(\\'|[^\n'])*')/,/^(?:([ \t]))/,/^(?:\n)/,/^(?:$)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59],"inclusive":true}}
});
return lexer;
})();
globalThis.LambdaLexer = llexer;
// TODO: pattern matching, computed attribute
// TODO: add state, stmt parsing only function

const TRACE = 0
const DUMP = 0

function nimpl(parser){
  console.error(parser.tokls.map(t => `[${t.type}]`).join(' '))
  console.trace();
  throw showError(parser.tokls[0],
    "SyntaxError: Not implement yet");
}

function validRegExp(pat){
  var ret = null;
  try {
    ret = new RegExp(pat);
  } catch(e) {
    ret = null;
  }
  return ret;
}

const event_types = [
  "me", "leave", "join", "newtab"
  , "msg", "dmto", "dm", "low"
  , "exittab", "exitalarm", "musicbeg", "musicend"
  , "music", "kick", "ban", "unban", "roll"
  // , "new-description", "new-host", "room-profile"
  , "description", "host", "profile"
  , "lounge", "*"]

const literalMap = {
  'true': true,
  'false': false,
  'null': null,
  'undefined': undefined,
}

const key_tokens = ["ident", "number", "string"];
const arith_tokens = ["+", "-"]
const term_tokens = ["**", "*", "/"]

// TODO support (...) operator
const assign_tokens = ["=", "+=", "-=", "**=", "*=", "/="
  , "%=", "<<=", ">>=", ">>>=", "&="
  , "^=", "|=", "&&=", "||=", "??="];

const equality_tokens = ["==", "!=", "===", "!=="];

const relational_tokens = [
  "<", "<=", ">", ">=", "in", "instanceof"];

const shift_tokens = ["<<", ">>", ">>>"];

const prefix14 = ["!", "~", "+", "-", "typeof", "void", "delete"];

function autoScope(expr){
  if(['group', 'arrow'].includes(expr.type))
    return expr;
  else
    return Group([expr], expr.tok);
}

function autoLambda(expr){
  if(['arrow'].includes(expr.type))
    return expr;
  else
    return Lambda([], expr, expr.tok);
}

// constructors
const State = (name, stmt, tok) => ({
  name, stmt: autoLambda(stmt), tok,
});

const Break = (tok) => ({
  type: 'break',
  tok,
})

const Continue = (tok) => ({
  type: 'continue',
  tok,
})

const Return = (val, tok) => ({
  type: 'return',
  val, tok,
})

const Visit = (state, args, tok) => ({
  type: 'visit',
  state, args, tok,
})

const Going = (state, args, tok) => ({
  type: 'going',
  state, args, tok,
})

const Push = (state, args, tok) => ({
  type: 'push',
  state, args, tok,
})

const Pop = (tok) => ({
  type: 'pop',
  tok,
})

const Event = (events, body, tok) => ({
  type: 'event',
  events, body: autoLambda(body), tok,
})

const Timer = (period, body, tok) => ({
  type: 'timer',
  period, body: autoLambda(body), tok,
})

const Later = (period, body, tok) => ({
  type: 'later',
  period, body: autoLambda(body), tok,
})

const Unary = (op, val, tok) => ({
  type: 'prefix', op, val, tok,
})

const Binary = (lval, op, rval, optChain, tok) => ({
  type: 'binary', lval, op, rval, optChain, tok
});

const Prefix = (op, val, tok) => ({
  type: 'prefix', op, val, tok,
});

const Postfix = (op, val, tok) => ({
  type: 'postfix', op, val, tok,
});

const LArray = (cells, tok) => ({
  type: "array", cells, tok,

})

const LObject = (pairs, tok) => ({
  type: "object", pairs, tok,

})

const Ifels = (cond, then, els, tok) => ({
  type: "ifels", cond, then, 'else': els, tok,
})

const Group = (stmts, tok) => ({
  type: 'group', body: stmts, tok,
});

const While = (cond, body, tok) => ({
  type: 'while', cond, body, tok
})

// const Floop

const Assignment = (lval, rval, tok) =>
  Binary(lval, "=", rval, false, tok);

const Call = (op, func, args, optChain, tok) => ({
  type: "call", op, func, args, optChain, tok
});

const Lambda = (pars = [], body, tok, tick) => ({
  type: "arrow", pars, body, tok, tick
});

const Val = (val, tok) => ({
  type: "val", val, tok,
});

const Var = (v, tok) => ({
  type: "var", var: v, tok,
})

const Sym = (v, tok) => ({
  type: "sym", sym: v, tok,
})

const Void = (tok) => Val(undefined, tok)

const Proc = (body, tok) => ({
  type: 'proc', body, tok: (tok || body.tok),
})

function liftImper(expr){
  if(['timer', 'later'].includes(expr.type)){
    // assert must be lambda
    if(expr.body.type !== 'arrow'){
      throw new MachineException(
          "ImplError", null, expr.body,
          `ImplError: timer & later body must be lifted as lambda`
        );
    }
    let lambda = expr.body
    expr.body = lambda.body;
    return Lambda(lambda.pars, expr, lambda.tok, lambda.tick);
  }
  else return Proc(expr);
}

function liftNF(expr){
  if(expr.type == 'arrow')
    return expr;
  return Lambda([], expr);
}

function liftGP(expr, tick){
  if(expr.type != 'group') return expr;
  let func = Lambda([], expr);
  func.tick = tick;
  return func;
}

function callOF(expr){
  if(expr.type == 'arrow')
    return Call("()", expr, []);
  return expr;
}

// parser attribute builder

const left_assoc = s => ({
  infix: s, assoc: { l: 1 }
});

const right_assoc = s => ({
  infix: s, assoc: { r: 1 }
});

const prefix = s => ({
  prefix: s
});

const postfix = s => ({
  postfix: s
});

const mustLval = s => ({
  mustLval: true, ...s
})

const noNL = s => ({
  noNL: true, ...s
})

// ( ... )
const between = s =>
  (open, close) => ({
    open, close
  });

// prefix postfix
// open   close
// right left

// ... ( ... ) or ... [ ... ]
const between_on =
  (left, right, times = 1, non_followed_by) => ({
    left, right, times, non_followed_by
  });

// new ... ( ... )
const prefix_between_on =
  (prefix, beg, end, optbe = false) => ({
    prefix, beg, end, optbe
  });

// ... ? ... : ...
// const ternary =
//   (cond, div) => ({
//     cond, div
//   });

const symP = (p) => {
  p.expect("ident");
  return Sym(p.token.val, p.token);
}

const lnext = lp => s => ({
  lnext: lp, ...s
});

const ops_precedences = [
  // move to expression
  // assign_tokens.map(right_assoc),
  [0,  ["||", "??"].map(left_assoc),
    [(pNoIn) => pNoIn, (pNoIn) => pNoIn]
  ],
  [1,  ["&&"].map(left_assoc),
    [(pNoIn) => pNoIn, (pNoIn) => pNoIn]
  ],
  [2,  ["|"].map(left_assoc),
    [(pNoIn) => pNoIn, (pNoIn) => pNoIn]
  ],
  [3,  ["^"].map(left_assoc),
    [(pNoIn) => pNoIn, (pNoIn) => pNoIn]
  ],
  [4,  ["&"].map(left_assoc),
    [(pNoIn) => pNoIn, (pNoIn) => pNoIn]
  ],
  [5,  equality_tokens.map(left_assoc),
    [(pNoIn) => pNoIn, (pNoIn) => pNoIn]
  ],
  [6,  relational_tokens.map(left_assoc),
    [(pNoIn) => pNoIn, (pNoIn) => false]
  ],
  [7,  shift_tokens.map(left_assoc)],
  [8,  ["+", "-"].map(left_assoc)],
  [9,  ["*", "/", "%"].map(left_assoc)],
  [10, ["**"].map(right_assoc)],
  [11, prefix14.map(prefix).concat(["++", "--"].map(prefix).map(mustLval))],
  [12, ["++", "--"].map(postfix).map(mustLval).map(noNL)],
  // [["new"].map(prefix)],
  // [[".", "?."].map(left_assoc)
  //             .map(lnext(symP))],
  // identifier name
  // [[lnext(symP)(left_assoc(".")),
  //   lnext(symP)(left_assoc("?.")),
  //   prefix_between_on("new", "(", ")"),
  //   between_on("[", "]"), between_on("(", ")")]],
  // [between("(", ")")]
];

function isLval(expr){
  return expr.type == 'var' ||
    expr.type == 'call' && expr.op == "[]" ||
    expr.type == "binary" && expr.op == ".";
}

function precedence_factory(
  parser, ops, next_ops, [NoInL, NoInR]){
  // may opt below because we can push
  // the correspoding op parsing function
  // instead of do if check (dispatch) in the function
  let prefixes = ops.filter(op => op.prefix);
  let infixes = ops.filter(op => op.infix);
  let postfixes = ops.filter(op => op.postfix);
  // let betweens = ops.filter(op => op.open);

  // let ternarys = ops.filter(op => op.cond);
  let btwnons = ops.filter(op => op.right);

  return function current_ops(NoIn){

    let next = parser.precedences[next_ops].bind(parser);

    for(let op of prefixes){
      if(!op.beg && (
        parser.accept(op.prefix) ||
        parser.reserved(op.prefix))){
        let pt = parser.token;
        let val = current_ops(NoIn);
        if(op.mustLval && !isLval(val))
          throw showError(this.token,
            `SyntaxError: Operand of ${op.prefix} must be a lval`);
        return Prefix(op.prefix, val, pt);
      }
    }

    // for(op of betweens){
    //   if(parser.accept(op.open)){
    //     // think
    //     let computed = parser.expr(0);
    //     parser.expect("]");
    //     return;
    //   }
    // }

    let matched_op = true;

    let lhs = null;

    for(let op of prefixes){
      if(op.beg && parser.reserved(op.prefix)){
        lhs = {
          type: "ctor",
          op: parser.token.val,
          func: null,
          args: [],
        }
        lhs.func = op.cnext();
        let arglist = [];
        if(op.optbe){
          if(parser.ahead_is(op.beg)){
            lhs.args = parser.list(
              () => parser.expr2(0),
              op.beg, op.end, ",", -1);
          }
          // else no arglist
        }
        else {
          lhs.args = parser.list(
              () => parser.expr2(0),
              op.beg, op.end, ",", -1);
        }
        break;
      }
    }

    lhs = lhs || next(NoInL && NoInL(NoIn));

    let optChain = false;
    let optChainTok = null;

    do {
      matched_op = false;
      for(let op of infixes){
        if(NoIn && op.infix == "in") continue;
        if(parser.accept(op.infix) ||
           parser.reserved(op.infix)){
          let bt = parser.token;
          if(op.assoc.l){
            if(op.infix == "?."){
              if(parser.accept("ident"))
                lhs = Binary(lhs, "?.",
                  Sym(this.token.val, this.token),
                  true, bt);
              else {
                optChain = true;
                optChainTok = bt;
              }
            }
            else {
              let rhs = op.lnext ?
                        op.lnext(parser, NoInR && NoInR(NoIn)) :
                        next(NoInR && NoInR(NoIn));
              lhs = Binary(lhs, op.infix, rhs, false, bt);
            }
            // node = [node, op.sym, rv];
            matched_op = true;
            break;
          }
          else if(op.assoc.r){
            return Binary(lhs, op.infix, current_ops(NoIn), false, bt);
            // return [node, op.sym, current_ops()];
          }
          else throw showError(bt,
            `SyntaxError: No assoc on infix operator ${op.infix}`);
        }
      }

      for(let op of btwnons){
        if(parser.ahead_is_see_nl(op.left)){

          let ct = parser.tokls[0];

          if(op.non_followed_by)
            parser.rb_record();

          let args = parser.list(
              () => parser[
                op.times == 1 ? 'expr' : 'expr2'
              ](),
              op.left, op.right, ",", op.times);

          if(op.non_followed_by){
            if(parser.ahead_is(op.non_followed_by)){
              parser.rb_reset();
              continue;
            }
            else parser.rb_erase();
          }
          matched_op = true;
          lhs = Call(
            `${op.left}${op.right}`,
            lhs, args, optChain, ct,
          );
          optChain = false;
          break;
        }
      }
    } while(matched_op);

    if(optChain)
      throw showError(optChainTok,
        `SyntaxError: Unexpected optChain expr,
?. should be followed by identifier, (..) or [...],
get ${JSON.stringify(parser.tokls[0].text, null, 2)}`)

    // for(let op of ternarys){
    //   if(parser.accept(op.cond)){
    //     current_ops(0);
    //     parser.expect(op.div);
    //     current_ops(NoIn);
    //     return; // something
    //   }
    // }

    for(let op of postfixes){
      // NOTE: no postfix op are reserved word
      let consume = op.noNL?
        () => parser.acceptNoNL(op.postfix):
        () => parser.accept(op.postfix);

      if(consume()){
        if(op.mustLval && !isLval(lhs))
          continue;
        return Postfix(op.postfix, lhs, parser.token);
      }
    }
    return lhs;
  }
}

function is_key_token(v){
  return key_tokens.includes(v);
}

function build_ops(parser){

  let newOp = prefix_between_on("new", "(", ")", true);
  let memberOps = [
    lnext(symP)(left_assoc(".")),
    left_assoc("?."),
    newOp, between_on("[", "]")]

  let memberExpression = precedence_factory(
      parser, memberOps, 13 + 1, []);

  newOp.cnext = memberExpression.bind(parser);

  let LeftHandSideExpression = [...memberOps, between_on("(", ")", -1, "=>")];

  let new_precs = [...ops_precedences
    , [13, LeftHandSideExpression]];

  new_precs.forEach(([prec, ops, NoIns]) => {
    parser.precedences[prec] = precedence_factory(
      parser, ops, prec + 1, NoIns || []);
  });

  parser.precedences[
    new_precs.length] = parser.factor;
}

class Parser {

  lexer = null;
  token = null;
  inLoop = false;
  tokls = [];
  precedences = {};
  rbpos = [];
  rbtoks = [];
  code = [];

  constructor(lexer){
    this.lexer = lexer;
    build_ops(this);
  }

  rb_record(){
    this.rbpos.push(this.rbtoks.length);
  }

  rb_erase(){
    this.rbpos.pop();
  }

  rb_reset(){
    let pos = this.rbpos.pop();
    this.tokls = this.rbtoks.splice(pos).concat(this.tokls);
  }

  next(ignore){
    if(!ignore && !this.tokls.length)
      throw showError(this.token,
        "SyntaxError: Zero length of token list on calling next()");

    if(!ignore){
      this.token = this.tokls.shift();
      if(this.rbpos.length)
        this.rbtoks.push(this.token);
      // console.log(`consume ${JSON.stringify(this.token, null, 2)}`)
    }

    if(!this.tokls.length){
      let tok = this.lexer.lex()
      this.tokls.push({
        type: tok,
        text: this.lexer.yytext,
        val: this.lexer.yylval,
        loc: {...this.lexer.yylloc},
        code: this.code,
      });
    }
  }

  peekNonNLIdx(){
    let i = 0;
    while(this.peek(i) == 'nl') i++;
    return i;
  }

  peekNonNL(idx = 0){
    let i = 0, acc = -1;
    while(this.peek(i) != 'EOF'){
      if(this.peek(i) != 'nl')
        acc++;
      if(acc == idx) return this.peek(i);
      i++;
    }
    return 'EOF';
  }

  acceptNoNL(...tokens){
    let p = this.peek();
    let ret = tokens.some(t => t == p);
    if(ret){
      this.next();
    }
    return ret;
  }

  acceptNLs(){
    while(this.peek() == 'nl')
      this.next();
  }

  // auto ignore nl
  accept(...tokens){
    // check if empty tokls
    if(tokens.includes(this.peekNonNL()))
      this.acceptNLs();
    return this.acceptNoNL(...tokens);
  }

  expect(token){
    // console.log(`expect ${token}`)
    if(!this.accept(token)){
      if(TRACE) console.trace();
      throw showError(this.tokls[0],
        `SyntaxError: Expected token [${token}], get [${this.peekNonNL()}]`)
    }
    return this.token.val;
  }

  ahead_is_see_nl(...args){
    // check if empty tokls
    return args.includes(this.peek());
  }

  ahead_is(...args){
    // check if empty tokls
    return args.includes(this.peekNonNL());
  }

  ahead_is_reserved(...args){
    let idx = this.peekNonNLIdx()
    return this.peek(idx) == 'ident'
      && args.includes(this.tokls[idx].val);
  }

  ahead_is_object(){
    return this.aheads_are("{", "}")
        || this.aheads_are("{", is_key_token, ":")
        || this.aheads_are("{", "ident", ",")
        || this.aheads_are("{", "ident", "}")
  }

  aheads_are(...args){
    // check if empty tokls
    return args.every((v, i) =>
      typeof v == 'function' ?
      v(this.peekNonNL(i)) : v == this.peekNonNL(i));
  }

  peek(k = 0){
    while(!this.lexer.done && k >= this.tokls.length){
      let tok = this.lexer.lex()
      this.tokls.push({
        type: tok,
        text: this.lexer.yytext,
        val: this.lexer.yylval,
        loc: {...this.lexer.yylloc},
        code: this.code,
      });
    }
    return k >= this.tokls.length ?
      null : this.tokls[k].type;
  }

  parse(code, noCheckState){
    code = code.trimEnd();
    this.code = code.split("\n");
    this.lexer.setInput(code);
    this.lexer.opt_t = false;
    this.tokls = [];

    let sym = null;
    if(DUMP) do{
      sym = this.lexer.lex();
      // if(sym == "string")
      //   console.log(this.lexer.yylval);
      // console.log(this.lexer.done)
    } while(sym != "EOF");
    else return this.script(noCheckState);
  }

  list(item, beg, end, delimiter = ",", times = -1, opt = false){
    let ret = [];
    if(opt && this.ahead_is_see_nl(beg))
      return [];
    this.expect(beg)
    let token = this.token;
    while(!this.accept(end)){
      if(times == 0) throw showError(token,
        `SyntaxError: Too may exprs in ${beg}...${end}`);
      ret.push(item());
      if(times > 0) times -= 1;

      if(times == 0){
        this.expect(end);
        break;
      }
      else if(this.accept(end)) break;

      this.expect(delimiter);
      if(this.accept(end)) break;
    }
    if(times > 0) throw showError(token,
      `SyntaxError: Insufficient exprs in ${beg}...${end}`)
    return ret;
  }

  // start of the parsing rules

  factor(NoIn){
    // array literal, parens

    let inLoop = this.inLoop;
    this.inLoop = false;
    let ret = this.imperative(1);
    this.inLoop = inLoop;

    if(ret) return liftImper(ret);

    // keyword (reserved word) that cannot be factor
    if(this.reserved(
      ...[ "while", "for", "timer", "later",
        "going", "visit", "push", "pop", // "state", "event",
        "in", "instanceof", "typeof", "void",
        "new", "delete", "if", "then", "else",
        "break", "continue", "return" ])){
      throw showError(this.token,
        `SyntaxError: Unexpected token '${this.token.val}'`);
    }
    else if(this.accept("number", "string")){
      return Val(this.token.val, this.token);
    }
    else if(this.reserved(
      "true", "false", "null", "undefined")){
      return Val(literalMap[this.token.val], this.token);
    }
    else if(this.accept("ident")){
      return Var(this.token.val, this.token);
    }
    else if(this.accept("(")){
      let val = this.expr(0);
      this.expect(")");
      return val;
    }
    else if(this.ahead_is("[")){
      let at = this.tokls[0];
      return LArray(this.list(
          () => this.expr2(0), "[", "]", ",", -1), at);
    }
    // object
    else if(this.ahead_is("{")){
      return this.object(0);
    }
    else {
      let idx = this.peekNonNLIdx();
      throw showError(this.tokls[idx],
        `SyntaxError: Unexpected token, expected factor`);
    }
  }

  object(NoIn){
    // console.log(`peek ${this.peek()}`);
    // console.log(this.tokls)
    let pairs = [];
    this.expect("{");
    let ot = this.token;
    while(!this.accept("}")){
      if(this.accept.apply(this, key_tokens)){
        let k = this.token.val;
        this.expect(":");
        let v = this.expr2(0);
        pairs.push([k, v]);
        if(this.accept("}")) break;
        this.expect(",");
        if(this.accept("}")) break;
      }
      else {
        let idx = this.peekNonNLIdx();
        throw showError(this.tokls[idx],
          `SyntaxError: Expected an object key`);
      }
    }
    return LObject(pairs, ot);
  }

  assignment(NoIn){

    let LogicalORExpression = this.precedences[0].bind(this);

    let mayLHS = LogicalORExpression(NoIn);

    // LHSexpr
    // { ids } op=
    // [ ids ] op=
    // Logical

    if(this.accept.apply(this, assign_tokens)){
      let bt = this.token;
      let op = this.token.val;
      if(!isLval(mayLHS))
        throw showError(bt,
          `SyntaxError: Operand of ${op} must be a lval`);
      return Binary(mayLHS, op, this.expr(NoIn), false, bt);
    }
    else if(this.accept("?")){
      let qt = this.token;
      let tn = this.expr(0);
      this.expect(":");
      let es = this.expr(NoIn);
      return Ifels(mayLHS, tn, es, qt);
    }
    else return mayLHS;
  }

  expr2(NoIn){
    // ( ids ) =>
    if(this.reserved("if")){
      let it = this.token;
      let ret = Ifels(
        this.expr(0),
        undefined,
        undefined, it);
      let thenTok = null;
      if(this.reserved("then")){
        thenTok = this.token;
      }
      ret.then = this.stmt(true);
      if(thenTok) ret.then.tok = thenTok;
      if(this.reserved("else"))
        ret.else = this.stmt(true);
      return ret;
    }
    else if(this.aheads_are("ident", "=>")
      || this.aheads_are("ident", ":")
      || this.aheads_are("(", ")", "=>")
      || this.aheads_are("(", "ident", ",", "=>")
      || this.aheads_are("(", "ident", ":")
      || this.aheads_are("(", "ident", ",")
      || this.aheads_are("(", "ident", ")", "=>")
    ){
      let inLoop = this.inLoop;
      this.inLoop = false;
      let ret = Lambda();
      // ident =>
      // ident : expr =>
      // ( ) =>
      // ( ident # , ident # =>
      // ( ident :
      // ( ident ,
      if(this.accept("(")){
        while(!this.accept(")")){
          let sym = this.expect("ident");
          let pat = this.accept(":") ?
                    this.expr2(0) : undefined;

          if(pat && pat.type == 'val' && typeof pat.val == 'string'){
            let regexp = validRegExp(pat.val)
            if(regexp) pat.val = regexp;
            else throw showError(pat.token,
              `SyntaxError: "${pat.val}" is not a valid RegExp`);
          }

          ret.pars.push([sym, pat]);
          if(this.accept(")")) break;
          this.expect(",");
          if(this.accept(")")) break;
        }
      }
      else{
        let sym = this.expect("ident");
        let pat = this.accept(":") ?
                  this.expr(0) : undefined;

        if(pat && pat.type == 'val' && typeof pat.val == 'string'){
          let regexp = validRegExp(pat.val)
          if(regexp) pat.val = regexp;
          else throw showError(pat.token,
            `SyntaxError: "${pat.val}" is not a valid RegExp`);
        }

        ret.pars.push([sym, pat]);
      }
      this.expect("=>");
      ret.tok = this.token;
      // no comma
      ret.body = this.stmt(true);
      this.inLoop = inLoop;
      return ret;
    }
    else return this.assignment(NoIn);
  }

  expr(NoIn){
    // ( ids ) =>
    let lhs = this.expr2(NoIn);
    while(this.accept(",")){
      let bt = this.token;
      lhs = Binary(lhs, ",", this.expr(NoIn), false, bt);
    }
    return lhs;
  }

  optAccept(v, s){
    this.accept(s);
    return v;
  }

  floop(){
    let ft = this.token;

    let parens = this.accept("(");

    let ret = { type: 'floop' };

    let init = this.accept(";") ?
               Void(this.token) :
               this.optAccept(this.expr(1), ";");

    if(this.reserved("in")){
      if(!isLval(init))
        throw showError(init.tok,
          `SyntaxError: For ... in must be a lval`);
      ret['var'] = init;
      ret['iter'] = [this.expr(0), 'keys'];
      if(parens) this.expect(")");
    }
    else if(this.reserved("of")){
      if(!isLval(init))
        throw showError(init.tok,
          `SyntaxError: For ... of must be a lval`);
      ret['var'] = init;
      ret['iter'] = [this.expr(0), 'values'];
      if(parens) this.expect(")");
    }
    else {
      ret['init'] = init;
      ret['cond'] = this.accept(";") ?
                    Void(this.token) :
                    this.optAccept(this.expr(0), ";");
      if(!parens){
        ret['step'] = this.expr(0);
      }
      else if(!this.accept(")")){
        ret['step'] = this.expr(0);
        this.expect(")");
      }
    }
    ret['body'] = this.stmt();
    ret['tok'] = ft;
    return ret;
  }

  events(){
    let ret = [];
    let parseE = (function(){
      if(this.accept("ident")){
        if(!event_types.includes(this.token.val))
          throw showError(this.token,
            `SyntaxError: Expected a event type, get: ${this.token.val}`);
        ret.push(this.token.val);
      }
      else if(this.accept("string")){
        if(!event_types.includes(this.token.val))
          throw showError(this.token,
            `SyntaxError: Expected a event type, get: ${this.token.val}`);
        ret.push(this.token.val);
      }
      else if(this.accept("*")){
        ret.push(this.token.val);
      }
      else {
        let idx = this.peekNonNLIdx();
        throw showError(this.tokls[idx],
          `SyntaxError: Expected a event type`);
      }
    }).bind(this);

    if(this.ahead_is("[")){
      this.list(parseE, "[", "]");
    }
    else parseE();
    return ret;
  }

  reserved(...symbol){
    // state event later timer going visit
    let idx = this.peekNonNLIdx()
    if(this.peek(idx) == 'ident'
      && symbol.includes(this.tokls[idx].val))
      return this.accept("ident");
    return false;
  }

  imperative(noLift = 0){
    let ret = null;
    if(this.reserved("while")){
      let inLoop = this.inLoop;
      this.inLoop = true;
      let st = this.token;
      ret = While(this.expr(0), this.stmt(), st);
      this.inLoop = inLoop;
    }
    else if(this.reserved("for")){
      let inLoop = this.inLoop;
      this.inLoop = true;
      ret = this.floop();
      this.inLoop = inLoop;
    }
    else if(this.reserved("timer")){
      let inLoop = this.inLoop;
      this.inLoop = false;
      let st = this.token;
      ret = Timer(this.expr(0), this.stmt(), st);
      this.inLoop = inLoop;
    }
    else if(this.reserved("later")){
      let inLoop = this.inLoop;
      this.inLoop = false;
      let st = this.token;
      ret = Later(this.expr(0), this.stmt(), st);
      this.inLoop = inLoop;
    }
    else if(this.reserved("event")){
      let inLoop = this.inLoop;
      this.inLoop = false;
      let st = this.token;
      ret = Event(this.events(), this.stmt(), st);
      this.inLoop = inLoop;
    }
    else if(this.reserved("going")){
      let st = this.token;
      let sym = this.expect("ident");
      let stateTok = this.token;
      let args = [];
      if(this.ahead_is_see_nl('(')){
        args = this.list(
          () => this.expr2(0),
          '(', ')', ",", -1);
      }
      ret = Going(sym, args, st);
      this.meet_states.push([ret.state, stateTok])
    }
    else if(this.reserved("visit")){
      let st = this.token;
      let sym = this.expect("ident");
      let stateTok = this.token;
      let args = [];
      if(this.ahead_is_see_nl('(')){
        args = this.list(
          () => this.expr2(0),
          '(', ')', ",", -1);
      }
      ret = Visit(sym, args, st);
      this.meet_states.push([ret.state, stateTok])
    }
    else if(this.reserved("push")){
      let st = this.token;
      let sym = this.expect("ident");
      let stateTok = this.token;
      let args = [];
      if(this.ahead_is_see_nl('(')){
        args = this.list(
          () => this.expr2(0),
          '(', ')', ",", -1);
      }
      ret = Push(sym, args, st);
      this.meet_states.push([ret.state, stateTok])
    }
    else if(this.reserved("pop")){
      let st = this.token;
      ret = Pop(st);
    }
    // block
    else if(this.ahead_is("{")
      && !(this.ahead_is_object())){
      this.expect("{");
      ret = Group([], this.token);
      while(!this.accept("}")){
        ret.body.push(this.stmt());
      }
    }
    else if(!noLift){
      if(this.reserved("return")){
        //TODO: do function check
        let st = this.token;
        let nt = this.peek(0);
        if(this.ahead_is_see_nl(';', 'nl', 'EOF'))
          ret = Return(Val(undefined, this.tokls[0]), st);
        else
          ret = Return(this.expr(), st);
      }
      else if(this.reserved("continue")){
        let st = this.token;
        //TODO: do in loop check
        if(!this.inLoop){
          throw showError(st,
            "SyntaxError: Break must be in a loop");
        }
        ret = Continue(st);
      }
      else if(this.reserved("break")){
        let st = this.token;
        //TODO: do in loop check
        if(!this.inLoop){
          throw showError(st,
            "SyntaxError: Break must be in a loop");
        }
        ret = Break(st);
      }
    }
    return ret;
  }

  let_list(){
    let ret = null, ct = null;
    this.reserved("let");
    while(1){
      this.expect("ident");
      let vt = this.token;
      let dec = Var(vt.val, vt);
      if(this.accept("=")){
        let et = this.token;
        dec = Assignment(dec, this.expr2(), et);
      }
      else dec = Assignment(dec, Val(undefined), dec.token);
      dec.let = true;
      ret = ret ? Binary(ret, ",", dec, false, ct) : dec;
      if(!this.accept(",")) break;
      ct = this.token;
    }
    return ret;
  }

  stmt(noComma){
    if(this.accept(";")){
      return Group([], this.token);
    }

    let ret = this.imperative();

    if(!ret){
      if(this.ahead_is_reserved("let")
        && this.peekNonNL(1) == "ident"){
        ret = this.let_list();
      }
    }

    if(!ret){
      ret = noComma ?
      this.expr2(0):
      this.expr(0);
    }

    this.accept(";");
    return ret;
  }

  state(){
    let st = this.token;
    return State(this.expect("ident"), this.stmt(), st);
  }

  states(){
    let ss = [];
    while(this.reserved("state"))
      ss.push(this.state());
    return ss;
  }

  stmts(){
    let ss = [];
    while(!
      (this.ahead_is_reserved("state")
        || this.ahead_is("EOF"))){
      ss.push(this.stmt());
    }
    return ss;
  }

  script(noCheckState = false){
    this.next(true);
    let states = [], stmts = [];
    this.meet_states = [];
    do{
      states.push.apply(states, this.states())
      stmts.push.apply(stmts, this.stmts())
    } while(!this.accept("EOF"));

    if(!noCheckState){
      let error = '';
      for(let [name, tok] of this.meet_states){
        let s = states.find(s => s.name == name);
        if(!s)
          error += (error ? '\n' : '') + showError(tok,
            `StateNotFound: Cannot find state ${name}`);
      }
      delete this.meet_states;
      if(error) throw error;
    }
    return { states, stmts };
  }
}

function strLen(str) {
  var l = str.length;
  var c = '';
  var length = 0;
  for (var i = 0; i < l; i++) {
    c = str.charCodeAt(i);
    if (0x0000 <= c && c <= 0x0019) {
      length += 0;
    } else if (0x0020 <= c && c <= 0x1FFF) {
      length += 1;
    } else if (0x2000 <= c && c <= 0xFF60) {
      length += 2;
    } else if (0xFF61 <= c && c <= 0xFF9F) {
      length += 1;
    } else if (0xFFA0 <= c) {
      length += 2;
    }
  }
  return length;
}

function showError(tok, message, color = true, arrow = true){
  if(!tok) return message;

  // if color, then no idicator
  // check color is on console or html
  if(color === true){
    if(typeof process != 'undefined')
      color = ["\x1b[31m", "\x1b[0m"]
    else color = ["<span style='color:red'>", "</span>"]
  }

  let loc = tok.loc;
  let ret = `${loc.first_line}:${loc.first_column}: ${message}\n`;
  for(let l = loc.first_line - 1; l < loc.last_line; l++){
    let indicator = '';
    let code = tok.code[l];

    if(l == loc.first_line - 1)
      indicator += ' '.repeat(strLen(code.substring(0, loc.first_column)))

    let beg = l == loc.first_line - 1 ? loc.first_column : 0;
    let end = l == loc.last_line - 1 ? loc.last_column : l.length;

    if(end - beg)
      indicator += '^'.repeat(end - beg);
    else
      indicator += ' ^';

    if(color){
      let [begTag, endTag] = color;
      code = code.substring(0, beg)
           + begTag + code.substring(beg, end) + endTag
           + code.substring(end);
    }

    ret += `${String(l + 1).padStart(5)} | ${code}\n`;

    if(arrow) ret += `      | ${indicator}\n`;
  }
  return ret.slice(0, -1);
}

function showCode(tok, message, color = true, arrow = false){
  if(!tok) return message;

  // if color, then no idicator
  // check color is on console or html
  if(color === true){
    if(typeof process != 'undefined')
      color = ["\x1b[34m", "\x1b[0m"]
    else color = ["<span style='color:red'>", "</span>"]
  }

  let loc = tok.loc;
  let ret = `${loc.first_line}:${loc.first_column}: ${message}\n`;
  for(let l = loc.first_line - 1; l < loc.last_line; l++){
    let indicator = '';
    let code = tok.code[l];

    if(l == loc.first_line - 1)
      indicator += ' '.repeat(strLen(code.substring(0, loc.first_column)))

    let beg = l == loc.first_line - 1 ? loc.first_column : 0;
    let end = l == loc.last_line - 1 ? loc.last_column : l.length;

    if(end - beg)
      indicator += '^'.repeat(end - beg);
    else
      indicator += ' ^';

    if(color){
      let [begTag, endTag] = color;
      code = code.substring(0, beg)
           + begTag + code.substring(beg, end) + endTag
           + code.substring(end);
    }

    ret += `${String(l + 1).padStart(5)} | ${code}\n`;

    if(arrow) ret += `      | ${indicator}\n`;
  }
  return ret.slice(0, -1);
}

function removeTok(obj) {
  for(let prop in obj) {
    if (prop === 'tok')
      delete obj[prop];
    else if (typeof obj[prop] === 'object')
      removeTok(obj[prop]);
  }
  return obj;
}

// https://262.ecma-international.org/5.1/#sec-11.2 parsing
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence


// TODO: support code generation to js


// TODO: add stack trace on machine exception
// TODO complete break, continue, return
// TODO think about push pop state

function censor(censor){
  var i = 0;
  return function(key, value) {
    if(i !== 0 && typeof(censor) === 'object'
      && typeof(value) == 'object' && censor == value)
      return '[Circular]';
    if(i >= 29) // seems to be a harded maximum of 30 serialized objects?
      return '[Unknown]';
    ++i; // so we know we aren't using the original object anymore
    return value;
  }
}

const RUNNER_DUMP = false;
const NONE = undefined;

function MachineException(type, value,
  token = null, message = "") {
  this.type = type;
  this.val = value;
  this.tok = token;
  this.message = message;
}

MachineException.prototype.toString = function() {
  return "MachineException: " + this.type + '"';
}

/* utility functions */
function padArray(array, length, fill){
  return array.concat(Array(Math.max(
    length - array.length, 0)).fill(fill));
}

function evalUnary(op, val, tok){
  if(op == "!")
    return (!val);
  else if(op == '~')
    return (~val);
  else if(op == '+')
    return (+val);
  else if(op == '-')
    return (-val);
  else if(op == 'typeof')
    return (typeof val);
  else if(op == 'void')
    return (void val);

  throw new MachineException(
    "ImplError", null, tok,
    `ImplError: Unsupported unary operator ${op}`
  );
}

function evalBinary(op, lval, rval, tok){
  if(op == "%")
    return (lval % rval);
  else if(op == "/")
    return (lval / rval);
  else if(op == '*')
    return (lval * rval);
  else if(op == '+')
    return (lval + rval);
  else if(op == '-')
    return (lval - rval);
  else if(op == '**')
    return (lval ** rval);
  else if(op == '>')
    return (lval > rval);
  else if(op == '>=')
    return (lval >= rval);
  else if(op == '<')
    return (lval < rval);
  else if(op == '<=')
    return (lval <= rval);
  else if(op == '==')
    return (lval == rval);
  else if(op == '!=')
    return (lval != rval);
  else if(op == '===')
    return (lval === rval);
  else if(op == '!==')
    return (lval !== rval);
  else if(op == "|")
    return (lval | rval);
  else if(op == "^")
    return (lval ^ rval);
  else if(op == "&")
    return (lval & rval);
  else if(op == "<<")
    return (lval << rval);
  else if(op == ">>")
    return (lval >> rval);
  else if(op == ">>>")
    return (lval >>> rval);
  else if(op == 'in'){
    if(!(rval instanceof Object))
      throw new MachineException(
        "TypeError", op, tok,
        `TypeError: Cannot use 'in' operator to search for ${lval} in ${rval}`
      );
    return (lval in rval);
  }
  else if(op == 'instanceof')
    return (lval instanceof rval);
  else if(op == ',')
    return rval;

  throw new MachineException(
    "ImplError", null, tok,
    `ImplError: Unsupported binary operator ${op}`
  );
}

let nextTimerOwnerId = 0;

class Machine {
  constructor(script, error = console.error.bind(console)){
    let {states, stmts} = script
      || {states: [], stmts: []};
    this.cur = "";
    this.tick = 0;
    this.val = NONE;
    this.timers = {};
    this.laterTimers = new Set();
    this.timerTasks = 0;
    this.timerOwnerId = ++nextTimerOwnerId;
    this.events = {};
    let top = pushEnv();
    this.top = insert(top, "top", top.tab)
    this.states = states;
    this.scops = [stmts];
    this.stmts = null;
    this.stmt = null;
    this.env = this.top;
    this.error = error;
    this.stateStack = [];
  }

  destructor(){
    this.clearAllTimer();
    this.clearAllLater();
    this.clearAllEvent();
  }

  startTimerTask(){
    if(this.timerTasks++ === 0
      && typeof globalThis.__drrrLambdaTimerActivityChanged === 'function')
      globalThis.__drrrLambdaTimerActivityChanged(this.timerOwnerId, true);
  }

  finishTimerTask(){
    if(this.timerTasks > 0 && --this.timerTasks === 0
      && typeof globalThis.__drrrLambdaTimerActivityChanged === 'function')
      globalThis.__drrrLambdaTimerActivityChanged(this.timerOwnerId, false);
  }

  setTimer(state, prd, act){
    this.timers[state] = this.timers[state] || [];
    this.startTimerTask();
    this.timers[state].push(setInterval(act, prd));
  }

  setLater(prd, act){
    this.startTimerTask();
    let id = setTimeout(() => {
      this.laterTimers.delete(id);
      try { act(); }
      finally { this.finishTimerTask(); }
    }, prd);
    this.laterTimers.add(id);
    return id;
  }

  clearTimer(state){
    if(this.timers[state])
      for(let id of this.timers[state]){
        clearInterval(id);
        this.finishTimerTask();
      }
    this.timers[state] = [];
  }

  clearAllTimer(){
    for(let s in this.timers) this.clearTimer(s);
  }

  clearAllLater(){
    for(let id of this.laterTimers){
      clearTimeout(id);
      this.finishTimerTask();
    }
    this.laterTimers.clear();
  }

  clearAllEvent(){
    this.cur = "";
    this.events = {};
  }

  listen(types, next){
    let state = this.cur;
    this.events[state] = this.events[state] || [];
    this.events[state].push([types, next])
  }

  tryUndef(ev){
    let val = NONE;
    try {
      val = ev();
    }
    catch(e){
      if(e.type == "ReferenceError"){
        return undefined;
      }
      throw e;
    }
    return val;
  }

  // may throw exception, and execute need catch it
  eval(env, expr){
    switch(expr.type){
      case 'arrow': {
        let vars = expr.pars.map(([v, p]) => v)
        let guards = expr.pars.map(([v, p]) => p)
                         .map(p => p && this.eval(env, p));
        for(let i = 0; i < guards.length; i++){
          let g = guards[i];
          if(!['function', 'string', 'undefined'].includes(typeof g)
            && !(g instanceof RegExp)){
            throw new MachineException(
              "TypeError", g, expr.pars[i][1].tok,
              `TypeError: Function guard must be function or string or undefined, get ${typeof g}`);
          }
          if(typeof g == 'string'){
            let regexp = validRegExp(g)
            if(regexp) guards[i] = regexp;
            else throw new MachineException(
              "TypeError", g, expr.pars[i][1].tok,
              `TypeError: "${g}" is not a valid RegExp`
            );
          }
        }
        return (_env => {
          let f = (...args) => {
            for(let i = 0; i < guards.length; i++){
              let g = guards[i];
              if(typeof g == 'function' && !g(args[i]))
                return NONE;
              else if(g instanceof RegExp){
                if(typeof args[i] !== 'string'
                  || !args[i].match(g))
                  return NONE;
              }
              else if(typeof g === 'undefined')
                continue;
              else throw new MachineException(
                "TypeError", g, expr.pars[i][1].tok,
                `TypeError: Invalid guard type ${typeof g}`
              );
            }
            let newEnv = pushEnv(_env);
            insert(newEnv, 'args', args);
            vars.forEach((sym, idx) => {
              insert(newEnv, sym, args[idx]);
            })
            let [ok, val] = this.execute(
              newEnv, [[expr.body]], expr.tick || -1);
            return ok ? val : NONE;
          }
          f.toString = () => showCode(expr.tok, '[function]');
          return f;
        })(env);
      }
      case 'ifels': {
        if(this.eval(env, expr.cond)){
          let [ok, val] = this.execute(env, [[expr.then]])
          if(ok == 'return')
            throw new MachineException(
              "Return", [ok, val], expr.then.tok,
              `Return: ${val}`);
          else if(ok == 'break'){
            throw new MachineException(
               "Break", val, val.tok,
               `Break`);
          }
          else if(ok == 'continue'){
            throw new MachineException(
               "Continue", val, val.tok,
               `Continue`);
          }
          else if(ok) return val;
          else {
              throw new MachineException(
              "CondError", NONE, expr.then.tok,
              "IfThenError: Something wrong with then statement"
            );
          }
        }
        else if(expr.else){
          let [ok, val] = this.execute(env, [[expr.else]])
          if(ok == 'return')
            throw new MachineException(
              "Return", [ok, val], expr.else.tok,
              `Return: ${val}`);
          else if(ok == 'break'){
            throw new MachineException(
               "Break", val, val.tok,
               `Break`);
          }
          else if(ok == 'continue'){
            throw new MachineException(
               "Continue", val, val.tok,
               `Continue`);
          }
          else if(ok) return val;
          else {
            console.log('====>', ok, val)
            throw new MachineException(
              "CondError", NONE, expr.else.tok,
              "IfElseError: Something Wrong with else statement"
            );
          }
        }
        else return NONE;
      }
      case 'prefix':
        if(expr.op == '++' || expr.op == '--'){
          // wrong ++ output on 'a'
          let val = this.eval(env, expr.val);
          if(expr.op == '++') ++val;
          else if(expr.op == '--') --val;
          return this.eval(env,
            Assignment(
              expr.val,
              Val(val, expr.val.tok),
              expr.tok));
        }
        else if(expr.op == 'delete'){
          let lhs = expr.val;
          if(lhs.type == 'binary' && lhs.op == '.'){
            let lval = this.eval(env, lhs.lval)
            let rval = lhs.rval.sym;
            if(typeof lval === 'undefined' || lval === null)
              throw new MachineException(
                "TypeError", lval, lhs.tok,
                `TypeError: Cannot read (.) properties of ${lval}`
              );
            return delete lval[rval];
          }
          else if(lhs.type == 'call' && lhs.op == '[]'){
            let lval = this.eval(env, lhs.func)
            let rval = this.eval(env, lhs.args[0]);
            if(typeof lval === 'undefined' || lval === null)
              throw new MachineException(
                "TypeError", lval, lhs.tok,
                `TypeError: Cannot read ([]) properties of ${lval}`
              );
            return delete lval[rval];;
          }
          else if(lhs.type == 'var'){
            let tab = assocTab(lhs['var']);
            if(tab) delete tab[lhs['var']];
          }
          return delete this.eval(env, expr.val);
        }
        else return evalUnary(expr.op, this.eval(env, expr.val), expr.tok);
      case 'postfix':
        if(expr.op == '++' || expr.op == '--'){
          // wrong ++ output on 'a'
          let val = this.eval(env, expr.val);
          let postval = val;
          if(expr.op == '++') postval++;
          else if(expr.op == '--') postval--;
          this.eval(env,
            Assignment(
              expr.val,
              Val(postval, expr.val.tok),
              expr.tok))
          return val;
        }
        throw new MachineException(
          "ImplError", null, expr.tok,
          `ImplError: Unsupported postfix operator ${expr.op}`
        );
      case 'binary':
        if(expr.op == '='){
          let lhs = expr.lval;
          if(lhs.type == 'binary' && lhs.op == '.'){
            let lval = this.eval(env, lhs.lval)
            let rval = lhs.rval.sym;
            if(typeof lval === 'undefined' || lval === null)
              throw new MachineException(
                "TypeError", lval, lhs.tok,
                `TypeError: Cannot read (.) properties of ${lval}`
              );
            return lval[rval] = this.eval(env, expr.rval);
          }
          else if(lhs.type == 'call' && lhs.op == '[]'){
            let lval = this.eval(env, lhs.func)
            let rval = this.eval(env, lhs.args[0]);
            if(typeof lval === 'undefined' || lval === null)
              throw new MachineException(
                "TypeError", lval, lhs.tok,
                `TypeError: Cannot read ([]) properties of ${lval}`
              );
            return lval[rval] = this.eval(env, expr.rval);
          }
          return (expr.let ? insert : save)(
            env, expr.lval['var'], this.eval(env, expr.rval));
        }
        else if(assign_tokens.includes(expr.op)){
          return this.eval(env,
            Assignment(
              expr.lval,
              Binary(
                expr.lval,
                expr.op.slice(0, -1),
                expr.rval,
                expr.tok
              ),
              expr.tok
            ));
        }
        else if(expr.op == '||'){
          return this.eval(env, expr.lval)
            || this.eval(env, expr.rval);
        }
        else if(expr.op == '??'){
          return this.tryUndef(() => this.eval(env, expr.lval))
            ?? this.eval(env, expr.rval);
        }
        else if(expr.op == '&&'){
          return this.eval(env, expr.lval)
            && this.eval(env, expr.rval);
        }
        else if(expr.op == '.'){
          let lval = this.eval(env, expr.lval);
          if(expr.optChain) return lval?.[expr.rval.sym];
          if(typeof lval === 'undefined' || lval === null)
            throw new MachineException(
              "TypeError", lval, expr.tok,
              `TypeError: Cannot read (.) properties of ${lval}`
            );
          return lval[expr.rval.sym];
        }
        else return evalBinary(
          expr.op,
          this.eval(env, expr.lval),
          this.eval(env, expr.rval),
          expr.tok,
        );
      case 'object': {
        let obj = {};
        // TODO support computable key
        for(let [k, v] of expr.pairs)
        obj[k] = this.eval(env, v);
        return obj;
      }
      case 'proc': {
        let func = Lambda([], expr.body, expr.tok, this.tick);
        return this.eval(env, func);
      }
      case 'array':
        return expr.cells.map(c => this.eval(env, c));
      case 'val':
        return expr.val;
      case 'var': {
        let val = NONE;
        try {
          val = assocVar(env, expr['var'])
        }
        catch(e){
          if(e.type == "ReferenceError"){
            e.val = expr['var'];
            e.tok = expr.tok;
          }
          throw e;
        }
        return val;
      }
      case 'ctor': {
        if(expr.op == 'new'){
          let func = this.eval(env, expr.func);
          let args = expr.args.map(arg => this.eval(env, arg));
          return new func(...args);
        }
        throw new MachineException(
          "ImplError", null, expr.tok,
          `ImplError: Unsupported constructor ${expr.op}`
        );
      }
      case 'call':
        if(expr.op == '()'){
          let lval = null, rvalTok = null;
          let callee = expr.func, func = null;
          if(callee.type == 'binary' && callee.op == '.'){
            lval = this.eval(env, callee.lval)
            let rval = callee.rval.sym;
            rvalTok = callee.rval.tok;
            if(typeof lval === 'undefined' || lval === null)
              throw new MachineException(
                "TypeError", lval, callee.tok,
                `TypeError: Cannot read (.) properties of ${lval}`
              );
            func = lval[rval];
          }
          else if(callee.type == 'call' && callee.op == '[]'){
            lval = this.eval(env, callee.func)
            let rval = this.eval(env, callee.args[0]);
            rvalTok = callee.args[0].tok;
            if(typeof lval === 'undefined' || lval === null)
              throw new MachineException(
                "TypeError", lval, callee.tok,
                `TypeError: Cannot read ([]) properties of ${lval}`
              );
            func = lval[rval];
          }
          else func = this.eval(env, expr.func);

          if(expr.optChain &&
            (typeof func == 'undefined'
              || func === null))
            return undefined;

          if(typeof func !== 'function')
            throw new MachineException(
              "TypeError", func, rvalTok ? rvalTok : expr.func.tok,
              `TypeError: ${func} is not a function (it is a ${typeof func})`
            );

          func = func.bind(lval);

          let args = expr.args.map(
            arg => this.eval(env, arg));
          return func(...args);
        }
        else if(expr.op == '[]'){
          let lval = this.eval(env, expr.func)

          if(typeof lval === 'undefined'
                 || lval === null){
            if(expr.optChain)
              return undefined;
            else throw new MachineException(
              "TypeError", lval, expr.tok,
              `TypeError: Cannot read ([]) properties of ${lval}`
            );
          }

          let rval = this.eval(env, expr.args[0]);
          return lval[rval];
        }
        throw new MachineException(
          "ImplError", null, expr.tok,
          `ImplError: Unsupported call ${expr.op}`
        );
      default:
        throw new MachineException(
          "ImplError", null, expr.tok,
          `ImplError: Invalid ${expr.type ||
              JSON.stringify(expr, censor(expr), 2)} expression`
        );
    }
  }

  // if setTick > 0, it wouldn't execute after the tick
  // if setTick == 0, it would only execute in the tick when it execute
  // if setTick < 0, it would execute whenever
  execute(env, scops, setTick){
    let ok, val = null;
    while(scops.length){
      try {
        [ok, val] = this.execute_(env, scops, setTick);
      }
      catch(e){
        if(e instanceof MachineException){
          if(e.type == 'Return'){
            return e.val;
          }
          else
            this.error(showError(e.tok, e.message));
        }
        else {
          this.error(e.stack);
        }
        return [false, undefined];
      }
    }
    return [ok, val];
  }

  findState(stmt){
    let state = this.states.find(s => s.name == stmt.state)
    if(!state) throw new MachineException(
      "StateNotFound", stmt.state, stmt.tok,
      `StateNotFound: Cannot ${stmt.type} state ${stmt.state}`);
    return state.stmt;
  }

  execute_(env, scops, setTick = 0){
    let val = NONE;
    let tick = this.tick;
    while(scops.length){
      let stmts = scops.shift();
      while(stmts.length){
        if(setTick > 0 && this.tick > setTick)
          return [false, undefined];
        else if(setTick == 0 && tick != this.tick)
          return [false, undefined];
        // if (setTick < 0 && true)
        // /* continue executing anyway */ ;

        let stmt = stmts.shift();
        val = NONE;
        switch(stmt.type){
          case 'return': {
            return ['return', this.eval(env, stmt.val)];
            break;
          }
          case 'break': {
            let found = false;
            while(1){
              let stmt = null;
              while(stmts.length){
                stmt = stmts.shift();
                if(stmt.type == 'while'){
                  found = true;
                  break;
                }
              }
              if(stmt && stmt.type == 'while')
                break;
              env = popEnv(env);
              if(!scops.length) break;
              stmts = scops.shift();
            }
            if(!found) return ['break', stmt];
            continue;
          }
          case 'continue': {
            let found = false;
            while(1){
              let stmt = null;
              while(stmts.length){
                stmt = stmts.shift();
                // if(stmt.type == 'while'){
                if(stmt.step || stmt.type == 'while'){
                  found = true;
                  break;
                }
              }
              // if(stmt && stmt.type == 'while'){
              if(stmt && (stmt.step || stmt.type == 'while')){
                stmts.unshift(stmt);
                break;
              }
              env = popEnv(env);
              if(!scops.length) break;
              stmts = scops.shift();
            }
            if(!found){
              return ['continue', stmt];
            }
            continue;
          }
          case 'push': {
            this.stateStack.push(
              [this.cur, scops, stmts, env]);
            if(this.cur.length)
              this.events[this.cur] = [];
            this.tick += 1;
            this.cur = stmt.state;
            let stateStmt = this.findState(stmt);
            let args = stmt.args.map(
              arg => this.eval(env, arg));
            if(stateStmt.type !== 'arrow'){
              throw new MachineException(
                  "ImplError", null, stateStmt,
                  `ImplError: state stmt must be lifted as lambda`
                );
            }
            stateStmt = Call("()", stateStmt,
              args.map((v, i) => Val(v, stmt.args[i].tok)));

            return this.execute(this.env, [[stateStmt]]);
            // setTimeout(() =>
            //   this.execute(this.env, [[stateStmt]]), 0);
            // return [false, undefined];
          }
          case 'pop': {
            // TODO: test if empty stack
            if(this.stateStack.length){
              this.tick += 1;
              tick = this.tick;
              [this.cur, scops, stmts, env] =
                this.stateStack.pop();
              continue;
            }
            else throw new MachineException(
              "StateError", null, stmt.tok,
              `StateError: call pop on empty state stack`
            );
          }
          case 'visit': {
            let stateStmt = this.findState(stmt);
            let args = stmt.args.map(
              arg => this.eval(env, arg));
            if(stateStmt.type !== 'arrow'){
              throw new MachineException(
                  "ImplError", null, stateStmt,
                  `ImplError: state stmt must be lifted as lambda`
                );
            }
            stateStmt = Call("()", stateStmt,
              args.map((v, i) => Val(v, stmt.args[i].tok)));
            stmts = [stateStmt].concat(stmts);
            break;
          }
          case 'going': {
            if(this.cur.length)
              this.events[this.cur] = [];
            this.tick += 1;
            this.cur = stmt.state;
            let stateStmt = this.findState(stmt);
            let args = stmt.args.map(
              arg => this.eval(env, arg));
            if(stateStmt.type !== 'arrow'){
              throw new MachineException(
                  "ImplError", null, stateStmt,
                  `ImplError: state stmt must be lifted as lambda`
                );
            }
            stateStmt = Call("()", stateStmt,
              args.map((v, i) => Val(v, stmt.args[i].tok)));
            setTimeout(() => {
              let [ok, val] =
                this.execute(this.env, [[stateStmt]])
                while(ok && typeof val == 'function')
                  val = val(...args);
            }, 0);
            return [true, undefined];
          }
          case 'event': {
            this.listen(
              stmt.events,
              (_env => (...args) => {
                // TODO: think if add tick on scop vs function
                let [ok, val] = this.execute(_env, [[stmt.body]]);
                while(ok && typeof val == 'function')
                  val = val(...args);
              })(env)
            )
            break;
          }
          case 'later':
            this.setLater(this.eval(env, stmt.period), (_env => () => {
              let [ok, val] = this.execute(_env, [[stmt.body]]);
              while(ok && typeof val == 'function')
                val = val();
            })(env));
            break;
          case 'timer':
            this.setTimer(
              this.cur,
              this.eval(env, stmt.period),
              (_env => () => {
                let [ok, val] = this.execute(_env, [[stmt.body]])
                while(ok && typeof val == 'function')
                  val = val();
              })(env)
            )
            break;
          case 'while':
            // NOTE: don't add scop,
            // scop will be added if the body is {}
            if(this.eval(env, stmt.cond)){
              stmts.unshift(stmt);
              stmts.unshift(stmt.body);
            }
            break;
          case 'floop':
            // NOTE: don't add scop,
            // scop will be added if the body is {}
            if(stmt['var']){
              if(!('iter' in stmt))
                throw new MachineException(
                  "ImplError", null, stmt.tok,
                  `ImplError: Unsupported for syntax`
                );
              let [obj, iterCall] = stmt.iter;
              let iter = Object[iterCall](this.eval(env, obj)).values();
              let step = Assignment(
                Var("@var"),
                Call("()",
                  Binary(
                    Var("@iter"),
                    ".", Sym("next")), [])
              );
              step.step = true;
              stmts.unshift(
                Group([
                  Assignment(Var("@iter"), Val(iter)),
                  Assignment(Var("@var"), Val(iter.next())),
                  While(
                    Unary("!",
                      Binary(Var("@var"), ".", Sym("done"))),
                    Group([
                      Assignment(stmt['var'],
                        Binary(Var("@var"), ".", Sym("value"))),
                      stmt.body,
                      step,
                    ])
                  )
                ])
              );
            }
            else if(stmt.init){
              let step = stmt.step;
              step.step = true;
              stmts.unshift(
                While(
                  stmt.cond,
                  Group([
                    stmt.body,
                    step,
                  ]),
                  stmt.tok));
              stmts.unshift(stmt.init);
            }
            else throw new MachineException(
              "ImplError", null, stmt.tok,
              `ImplError: Unsupported for syntax`
            );
            break;
          case 'group':
            scops.unshift(stmts);
            // NOTE: we need keep the body,
            // so clone a new body as stmts
            stmts = [...stmt.body];
            env = pushEnv(env);
            break;
          default: {
            try {
              val = this.eval(env, stmt);
            }
            catch(e){
              if(e instanceof MachineException
                && ['Break', 'Continue'].includes(e.type)){
                stmts.unshift(e.val);
              }
              else throw e;
            }
          }
        }
      }
      env = popEnv(env);
    }
    return [true, val];
  }

  loop(){
    let [ok, val] = this.execute(this.env, this.scops);
    if(ok) this.val = val;
    return [ok, val];
  }

  step(scops){
    let [ok, val] = this.execute(this.env, scops);
    if(ok) this.val = val;
    return [ok, val];
  }
}

function evalStmt(state, stmt){

}

function runStep(machine, code){

}

/* Environment functions */

function pushEnv(env){
  return {
    lv: (env && env.lv + 1) || 0,
    tab: {},
    root: env || null,
  }
}

function popEnv(env){
  return env && env.root;
}

function topEnv(env){
  if(!env) return env;
  while(env.root)
    env = env.root;
  return env;
}

function assocTab(env, key){
  while(env){
    if(key in env.tab)
      return env.tab;
    env = env.root;
  }
  return null;
}

function assocVar(env, name){
  while(env){
    if(name in env.tab)
      return env.tab[name];
    env = env.root;
  }
  if(name in globalThis)
    return globalThis[name];
  throw new MachineException(
    "ReferenceError", undefined, null,
    `ReferenceError: ${name} is not defined`
  );
}

// update a existed key
function update(env, key, val){
  let tab = assocTab(env, key);
  if(!tab) return false;
  tab[key] = val;
  return true;
}

// update or insert a key
function save(env, key, val){
  if(!env) return val;
  if(!update(env, key, val))
    env.tab[key] = val;
  return val;
}

// insert a new value only
function insert(env, key, val){
  if(!env) return env;
  env.tab[key] = val;
  return env;
}

/* exports */
function compile(code){
  let parser = new Parser({...LambdaLexer});
  let {states, stmts} = parser.parse(code);
  return [stmts];
}

function interact(machine, code){
  let parser = new Parser({...LambdaLexer});
  let {states, stmts} = parser.parse(code, true);
  return machine.step([stmts]);
}

function execute(code, error, dump = false){
  let parser = new Parser({...LambdaLexer});
  let script = parser.parse(code);
  if(dump)
    console.log(JSON.stringify(removeTok(script), null, 2))
  let machine = new Machine(script, error);
  let [ok, val] = machine.loop();
  return [ok, machine];
}


// DOC: new semantics of later and timer (while eval on return function)
// DOC: new syntax of later (later 1000() => drrr.log("hello")) is allowed
// DOC: statement keyword (sometimes event is keyword, sometimes variable?)
// DOC: new tick semantics on lambda and scoping (if continue executing based on states)
// DOC: console.log to drrr.log, no print, support drrr.repeat
// DOC: parsing difference between javascript:
// ```
// console.log
// (3)
// // print 3 in js, while treate no function invocation in lambda script
//
// [1,2,3]
// [0,1]
// // 2 in js ([1,2,3][1]), while treate as two array in lambda script
// ```
// DOC: break, continue, return, push, pop
// DOC: call on later, timer
// DOC: scoping (for i ..., i in a new scope)
//      default scope of i not global but local
// DOC: add let keyword
// TODO: sometimes the drrr.print or drrr.dm not work
// TEST: all lval check on compile time
// TEST: event callback like timer
// TEST: constraints in parameters
// TODO: suuport parameters in state (...) =>

globalThis.RL = { Machine, compile, execute, interact, insert };

})();
