// Generated by scripts/build-mv3-worker.mjs. Do not edit by hand.
globalThis.__drrrModules = Object.create(null);

// module/bgeffect.js
Object.defineProperty(globalThis.__drrrModules, "module/bgeffect.js", {
  configurable: true,
  get() {
    const module = (() => {
      "use strict";
      
      const ui = () => {
        return `
      <div class="input-group">
          <!--
          <div class="input-group-btn">
              <button class="btn btn-default" type="button">
                  <i class="glyphicon glyphicon-sort-by-order"></i>
              </button>
          </div>
          -->
      
          <span class="input-group-addon" style="width:0px; padding-left:0px; padding-right:0px; border:none;"></span>
      
          <div class="input-group-btn">
              <button id="snow" class="btn btn-default bgeffect" type="button" data-delayed-toggle="collapse">
                  <i class="glyphicon glyphicon-cloud"></i>
              </button>
              <button id="firework" class="btn btn-default bgeffect" type="button" data-delayed-toggle="collapse">
                  <i class="glyphicon glyphicon-fire"></i>
              </button>
              <button id="elevator" class="btn btn-default bgeffect" type="button" data-delayed-toggle="collapse">
                  <i class="glyphicon glyphicon-sort"></i>
              </button>
              <!--
              <button id="visualizer" class="btn btn-default bgeffect" type="button" data-delayed-toggle="collapse">
                  <i class="glyphicon glyphicon-cd"></i>
              </button>
              -->
          </div>
      </div>`
      }
      
      
      const ui_event = () => {
        $('.bgeffect').click(function(){
          sendTab({fn: bg_effect, args:{name: this.id}});
        });
      }
      
      //export const event_action = () => {
      //
      //}
      
      return {"ui": ui,
"ui_event": ui_event};
    })();
    Object.defineProperty(globalThis.__drrrModules, "module/bgeffect.js", {
      configurable: true,
      value: module,
    });
    return module;
  },
});

// module/echo.js
Object.defineProperty(globalThis.__drrrModules, "module/echo.js", {
  configurable: true,
  get() {
    const module = (() => {
      "use strict";
      
      const ui = () => {
        return `
      <div class="input-group">
          <div class="input-group-btn">
              <button class="btn btn-default" type="button">
                  <i class="glyphicon glyphicon-text-size"></i>
              </button>
          </div>
      
          <span class="input-group-addon" style="width:0px; padding-left:0px; padding-right:0px; border:none;"></span>
      
          <input id="echo_text" type="text" class="form-control" placeholder="text to echo">
      
          <div class="input-group-btn">
              <button id="echo_trigger" class="btn btn-default" type="button" title="echo">
                  <i class="glyphicon glyphicon-volume-up"></i>
              </button>
          </div>
      </div>`
      };
      
      const ui_event = () => {
        $('#echo_trigger').click(()=>{
          alert($("#echo_text").val());
          $("#echo_text").val('');
        });
      }
      
      
      const event_action = () => {
      
      }
      
      return {"ui": ui,
"ui_event": ui_event,
"event_action": event_action};
    })();
    Object.defineProperty(globalThis.__drrrModules, "module/echo.js", {
      configurable: true,
      value: module,
    });
    return module;
  },
});

// module/guess_number.js
Object.defineProperty(globalThis.__drrrModules, "module/guess_number.js", {
  configurable: true,
  get() {
    const module = (() => {
      "use strict";
      var GAME_GUESS_NUMBER = "GAME_GUESS_NUMBER"
      
      var language = window.navigator.userLanguage || window.navigator.language;
      var intro = (language == 'zh-CN' || language == 'zh-TW') ?
        `<p>在聊天室使用 <code>/start</code> 設定隨機數字，<br>或者你可以用上面的設定欄位設定（留空為隨機）</p><p>在聊天室發送四個數字開始猜數字。</p>`:`<p>Use <code>/start</code> in chatroom to set numbers randomly, <br>or you can use input above to set a number<br>(empty would be random)</p><p>Type four digits in chatroom to guess the number</p>`
      
      
      const ui = (config) => {
        return `
      <div class="input-group">
          <div class="input-group-btn">
              <button class="btn btn-default" type="button">
                  <i class="glyphicon glyphicon-sort-by-order"></i>
              </button>
          </div>
      
          <span class="input-group-addon" style="width:0px; padding-left:0px; padding-right:0px; border:none;"></span>
      
          <input id="answer" type="text" class="form-control" placeholder="Input 4 digits">
      
          <div class="input-group-btn">
              <button id="set_answer" class="btn btn-default" type="button"
                                                                     data-delayed-toggle="collapse" data-target="#music_list"
                                                                                                    title="set digits">
                  <i id="list_type" class="glyphicon glyphicon glyphicon-pencil"></i>
              </button>
              <button id="publish_set" class="btn btn-default" type="button" title="Announce Game">
                  <i class="glyphicon glyphicon-volume-up"></i>
              </button>
          </div>
      </div><br>${intro}`
      }
      
      
      const ui_event = (config) => {
        if(config[GAME_GUESS_NUMBER])
          $('#answer').val(config[GAME_GUESS_NUMBER]);
        $('#set_answer').click(()=>{
          gnset(
            $('#answer').val(),
            (v, msg)=>{
              !v && $('#answer').attr('placeholder', msg);
              !v && $('#answer').parent().addClass('has-error').removeClass('has-success');
              v && $('#answer').parent().addClass('has-success').removeClass('has-error');
              $('#answer').val(v);
            }
          );
        });
        $('#publish_set').click(()=>{
          sendTab({
            fn: publish_message,
            args: { msg: 'number setted, game start' }
          });
        });
      
      
      }
      
      const event_action = (req, config) => {
        var type = req.type;
        if(type == event_msg){
          if(req.text.match(/^\/start/))
            setTimeout(()=> sendTab({ fn: publish_message, args: { msg: gnset() } }), 1000);
          else if(req.text.match(/^\d\d\d\d$/))
            gnjdg(req.text, config,
              (msg) => setTimeout(()=>
                sendTab({ fn: publish_message, args: { msg: msg } }), 1000));
        }
      }
      
      /* GAME_GUESS_NUMBER EXAMPLE
      "msg", "", "^/start", "gnset", [""]
      "msg", "", "^\\d\\d\\d\\d$", "gnjdg", ["$cont"]
      */
      
      // export
      //action_gnset = "gnset"
      //action_gnjdg = "gnjdg"
      //action_actions.push(action_gnset)
      //action_actions.push(action_gnjdg)
      
      // game logic
      function valid(digits){
        return digits.match(/^\d\d\d\d$/) && (new Set(digits.split(''))).size === 4;
      }
      
      function gnset(digits, callback){
        if(!digits){
          do{ digits = String(Math.floor(1000 + Math.random() * 9000));
          } while(!valid(digits));
          chrome.storage.local.set({ [GAME_GUESS_NUMBER]: digits });
          callback && callback(digits, "random number set, game start");
          return "random number set, game start";
        }
        else if(valid(digits)){
          chrome.storage.local.set({ [GAME_GUESS_NUMBER]: digits });
          callback && callback(digits, "number set, game start")
          return "number set, game start";
        }
        else{
          chrome.storage.local.remove(GAME_GUESS_NUMBER);
          callback && callback('', `give me 4 different digits, you give me ${digits}`)
          return `give me 4 digits, you give me ${digits}`;
        }
      }
      
      function gnjdg(guess, config, callback){
        if(valid(guess)){
          if(config[GAME_GUESS_NUMBER]){
            var d = config[GAME_GUESS_NUMBER].split('');
            var g = guess.split('');
            var c = g.map((v)=>d.includes(v)).reduce((a, b)=>a+b);
            var a = g.map((v, idx)=>d[idx] === g[idx]).reduce((a, b)=>a+b);
            var b  = c - a;
            callback(a === 4 ? "Your Number is Correct" : `${guess}: ${a}A${b}B`);
          } else callback("number not set yet, set number to start the game.");
        } else callback(`guess number must be 4 non-repeat digits: ${guess}`);
      }
      
      return {"ui": ui,
"ui_event": ui_event,
"event_action": event_action};
    })();
    Object.defineProperty(globalThis.__drrrModules, "module/guess_number.js", {
      configurable: true,
      value: module,
    });
    return module;
  },
});

// module/hidden_lounge.js
Object.defineProperty(globalThis.__drrrModules, "module/hidden_lounge.js", {
  configurable: true,
  get() {
    const module = (() => {
      "use strict";
      var HIDDEN_LOUNGE = "HIDDEN_LOUNGE"
      
      var language = window.navigator.userLanguage || window.navigator.language;
      var intro = (language == 'zh-CN' || language == 'zh-TW') ?
        `<p>歡迎使用隱藏大廳模組，<br>可以填自己的 Google Sheet ID，<br>但要記得開 "共用" 和 "編輯權限"。</p>`:`<p>Welcome to Hidden Lounge Module,<br>you can use your own Google Sheet ID, <br>but remeber to provide the "edit permission".</p>`
      
      const ui = (config) => {
        return `
      <div class="input-group">
          <div class="input-group-btn">
              <button id="upload_room" class="btn btn-default" type="button" title="upload room">
                  <i class="glyphicon glyphicon-upload"></i>
              </button>
          </div>
      
          <span class="input-group-addon" style="width:0px; padding-left:0px; padding-right:0px; border:none;"></span>
      
          <input id="hidden_lounge_sheet_id" type="text" class="form-control" placeholder="Sheet ID">
      
          <div class="input-group-btn">
              <button id="set_sheet_id" class="btn btn-default" type="button"
                     data-delayed-toggle="collapse" data-target=""
                                                                                                    title="set sheet id">
                  <i id="" class="glyphicon glyphicon-pencil"></i>
              </button>
              <button id="go_lounge" class="btn btn-default" type="button"
                     data-delayed-toggle="collapse" data-target=""
                                                                                                    title="go to lounge">
                  <i id="" class="glyphicon glyphicon-log-in"></i>
              </button>
          </div>
      </div><br>${intro}`
      }
      
      const ui_event = (config) => {
      
        $('#hidden_lounge_sheet_id').val(config[HIDDEN_LOUNGE] || '');
      
        $('#set_sheet_id').click(()=>{
          chrome.storage.local.set({ [HIDDEN_LOUNGE]: $('#hidden_lounge_sheet_id').val() });
          alert("done");
        });
      
        $('#go_lounge').click(()=>{
          chrome.storage.local.get([HIDDEN_LOUNGE], cfg => {
            chrome.tabs.create({
              url: `https://drrrchatbots.gitee.io/peerjs/hidden-lounge.html?${cfg[HIDDEN_LOUNGE] ? `id=${cfg[HIDDEN_LOUNGE]}` : ''}`
            });
          });
        });
      
        $('#upload_room').click(()=>{
          upload(()=>alert("ok"), ()=>alert("error"));
        });
      }
      
      const event_action = (req, config) => {
        var type = req.type;
        console.log(req);
        if(req.start === 'room'){
          upload();
        }
        else if(type === event_join){
          upload();
        }
        else if(type === event_join){
          upload();
        }
      }
      
      function upload(succ, fail){
        let loungeURL = 'https://script.google.com/macros/s/AKfycbwaH1jCoYImuIxFaNqkrh5DcxoaAlL19V0WD_We8D4FA7OItepjCD9p/exec';
      
        getRoom(info => {
      
          if(!info.room || !info.room.hiddenRoom) return;
      
          var host = info.room.users.filter(u => u.id === info.room.host)[0];
      
          var room = [
            info.room.roomId,
            info.room.name,
            info.room.description,
            info.room.limit,
            info.room.total,
            host.name,
            host.icon,
            host.tripcode || '',
            info.room.update,
          ];
      
          chrome.storage.local.get([HIDDEN_LOUNGE], config => {
      
            var params = { data: JSON.stringify(room) };
            if(config[HIDDEN_LOUNGE])
              params.id = config[HIDDEN_LOUNGE];
            params.cmd = 'keep';
            $.ajax({
              type: "POST",
              url: loungeURL,
              dataType: 'json',
              data: params,
              success: function(data){
                succ ? succ(data) : console.log('logged:', data);
              },
              error: function(data){
                fail ? fail(data) : console.log('failed:', data);
              }
            });
          });
        });
      }
      
      return {"ui": ui,
"ui_event": ui_event,
"event_action": event_action};
    })();
    Object.defineProperty(globalThis.__drrrModules, "module/hidden_lounge.js", {
      configurable: true,
      value: module,
    });
    return module;
  },
});

// module/hidden_room.js
Object.defineProperty(globalThis.__drrrModules, "module/hidden_room.js", {
  configurable: true,
  get() {
    const module = (() => {
      "use strict";
      var HIDDEN_ROOM = "HIDDEN_ROOM"
      
      var language = window.navigator.userLanguage || window.navigator.language;
      var intro = (language == 'zh-CN' || language == 'zh-TW') ?
        `<p>歡迎使用隱藏房間模組。</p>`:`<p>Welcome to hidden room module.</p>`
      
      Object.defineProperty(String.prototype, 'hashCode', {
        value: function() {
          var hash = 0, i, chr;
          for (i = 0; i < this.length; i++) {
            chr   = this.charCodeAt(i);
            hash  = ((hash << 5) - hash) + chr;
            hash |= 0; // Convert to 32bit integer
          }
          return hash;
        }
      });
      
      const ui = (config) => {
        return `
        ${intro}
        <!--
        <div class="input-group">
          <div class="input-group-btn">
              <button id="trpg_host" class="btn btn-default" type="button" title="become host">
                  <i id="is_host" class="glyphicon glyphicon-user"></i>
              </button>
          </div>
      
          <span class="input-group-addon" style="width:0px; padding-left:0px; padding-right:0px; border:none;"></span>
      
          <input id="trpg_bg_url" type="text" class="form-control" placeholder="SCENE URL">
      
          <div class="input-group-btn">
              <button id="set_trpg_bg" class="btn btn-default" type="button"
                                                                     data-delayed-toggle="collapse" data-target=""
                                                                                                    title="set scene">
                  <i id="" class="glyphicon 	glyphicon-picture"></i>
              </button>
          </div>
        </div>
          -->
        <hr>
        <div class="row" style="height:100%">
          <div class="col-md-4">
            <div class="list-group" style="margin-bottom: 0px;">
              <div id='hidden_list_container'></div>
            </div>
          </div>
        </div>`
      }
      
      var goto_hidden_btn = (args) =>
        `<button class="btn btn-default goto-hidden" type="submit"
               data="${args.data}"   title="go to the hidden room">
           <i class="glyphicon glyphicon-remove"></i>
        </button>`
      
      function bind_del_enemy(args){
        $(`.goto-hidden[data="${args.data}"]`).click(function(){
          alert("gogogo");
          //chrome.storage.local.get([ENEMY], (config) =>{
          //  var enemy = config[ENEMY]
          //  enemy.splice(enemy.indexOf($(this).attr('data')), 1);
          //  chrome.storage.local.set({ [ENEMY]: enemy });
          //  show_hidden_list(config);
          //});
        });
      }
      
      const ui_event = (config) => {
      
        var doors = {'hidden_door': []};
        //Whisperd, check new room
        btn_funcbind[goto_hidden_btn] = bind_del_enemy;
        $.ajax({
          type: "GET",
          url: `https://drrr.chat/d/1324-hidden-room-dispatcher/10000`,
          dataType: 'html',
          success: function(data){
            var nodes = data.match(new RegExp(/<\s*noscript\s*id="flarum-content"\s*[^>]*>((.|\n)*?)<\s*\/\s*noscript>/g));
            for(var u of $($.parseHTML(nodes[0])).find('h3')){
              console.log(u.textContent, u.nextElementSibling.textContent.trim());
              const str = u.nextElementSibling.textContent.trim();
              const regexp = /feature:<(.*)> encoded:<(.*)>/g;
              const matches = [...str.matchAll(regexp)];
              if(matches[0]){
                console.log(matches);
                var [_, salt, encoded, ..._] = matches[0];
                console.log(salt, encoded);
                doors.hidden_door.push({user: u.textContent, salt: salt, id: encoded});
              }
            }
            show_hidden_list(doors);
          },
          error: function(data){
            if(data.status == 401){
              alert("you need login drrr.chat first");
              chrome.tabs.create({url: 'https://drrr.chat'});
            }
            else alert("fetch failed" + JSON.stringify(data));
          }
        });
      }
      
      const event_action = (req, config) => {
        var type = req.type;
        //var enemy = config[ENEMY];
        //var observe = config[OBSERVE];
        //if(!observe) observe = [];
        //if(!enemy) enemy = [];
        //if(type == event_join){
        //  if(enemy && enemy.includes(req.user)){
        //    setTimeout(()=> sendTab({ fn: ban_member, args: { user: req.user } }), 200);
        //  }
        //  else{
        //    if(!observe.includes(req.user)){
        //      observe.push(req.user);
        //      chrome.storage.local.set({ [OBSERVE]: observe });
        //      chrome.runtime.sendMessage({show_observe_list: true, config: config});
        //    }
        //  }
        //}
        //else if(type == event_leave && observe){
        //  if(observe.includes(req.user)){
        //    observe.splice(observe.indexOf(req.user), 1);
        //    enemy.push(req.user);
        //    chrome.storage.local.set({
        //      [OBSERVE]: observe,
        //      [ENEMY]: enemy
        //    });
        //    chrome.runtime.sendMessage({show_observe_list: true, show_hidden_list: true, config: config});
        //  }
        //}
        //else{
        //  if(observe && observe.includes(req.user)){
        //    observe.splice(observe.indexOf(req.user), 1);
        //    chrome.storage.local.set({ [OBSERVE]: observe });
        //    chrome.runtime.sendMessage({show_observe_list: true, config: config});
        //  }
        //}
      }
      
      // module logic
      //function show_observe_list(config){
      //  show_configlist(
      //    '#observe_list_container',
      //    OBSERVE, ()=>{},
      //    [],
      //    'EMPTY OBERSERVATION LIST', {
      //      title: (c, name) => `${name} is in observation`,
      //      content: (c, name) => `${name}`,
      //      data: (c, name) => `${name}`,
      //      icon: 'glyphicon-list'
      //    }, config);
      //}
      
      function show_hidden_list(config){
        show_configlist(
          '#hidden_list_container',
          'hidden_door', ()=>{},
          [goto_hidden_btn],
          'EMPTY HIDDEN ROOM LIST', {
            title: (c, e) => `try the hidden room - ${e.id} `,
            content: (c, e) => `${e.user + ": " + e.id}`,
            data: (c, e) => `${e.id}`,
            icon: 'glyphicon-list'
          }, config);
      }
      
      return {"ui": ui,
"ui_event": ui_event,
"event_action": event_action};
    })();
    Object.defineProperty(globalThis.__drrrModules, "module/hidden_room.js", {
      configurable: true,
      value: module,
    });
    return module;
  },
});

// module/none.js
Object.defineProperty(globalThis.__drrrModules, "module/none.js", {
  configurable: true,
  get() {
    const module = (() => {
      "use strict";
      
      //export const ui = () => {
      //
      //}
      //
      //
      //export const ui_event = () => {
      //
      //}
      //
      //export const event_action = () => {
      //
      //}
      
      return {};
    })();
    Object.defineProperty(globalThis.__drrrModules, "module/none.js", {
      configurable: true,
      value: module,
    });
    return module;
  },
});

// module/otoko.js
Object.defineProperty(globalThis.__drrrModules, "module/otoko.js", {
  configurable: true,
  get() {
    const module = (() => {
      "use strict";
      var GAME_OTOKO = "GAME_OTOKO"
      
      var language = window.navigator.userLanguage || window.navigator.language;
      var intro = (language == 'zh-CN' || language == 'zh-TW') ?
        `<p>假裝是一隻 otoko，支援時間格式語法。</p>`:`<p>Pretend otoko, support time format syntax.</p>`
      
      const ui = (config) => {
        return `
      <div class="input-group">
      
          <select id="otoko_lang" name="otoko_change_room" class="form-control" style="text-align:center;padding-left: 4px;padding-right: 0px;padding-top: 4px;" title="enable auto room changing">
            <option value="all">ALL Language</option>
            <option value="zh">中文</option>
            <option value="en-US">English</option>
            <option value="af-ZA">Afrikaans</option>
            <option value="ar-SA">العربية</option>
            <option value="bg-BG">Български</option>
            <option value="bn-BD">Bangla</option>
            <option value="ca-ES">Català</option>
            <option value="cs-CZ">Čeština</option>
            <option value="da-DK">Dansk</option>
            <option value="de-DE">Deutsch</option>
            <option value="el-GR">Ελληνικά</option>
            <option value="eo-UY">Esperanto</option>
            <option value="es-ES">Español</option>
            <option value="et-EE">Eesti</option>
            <option value="fi-FI">Suomi</option>
            <option value="fil-PH">Filipino</option>
            <option value="fr-FR">Français</option>
            <option value="he-IL">עברית‎</option>
            <option value="hr-HR">Hrvatski</option>
            <option value="hu-HU">Magyar</option>
            <option value="id-ID">Bahasa Indonesia</option>
            <option value="it-IT">Italiano</option>
            <option value="ja-JP">日本語</option>
            <option value="ka-GE">ქართული</option>
            <option value="ko-KR">한국어</option>
            <option value="lt-LT">Lietuvių</option>
            <option value="lv-LV">Latviešu</option>
            <option value="ms-MY">Bahasa Melayu</option>
            <option value="nl-NL">Nederlands</option>
            <option value="no-NO">Norsk bokmål</option>
            <option value="pl-PL">Polska</option>
            <option value="pt-BR">Português (Brazil)</option>
            <option value="pt-PT">Português</option>
            <option value="ro-RO">Română</option>
            <option value="ru-RU">Русский</option>
            <option value="sk-SK">Slovenčina</option>
            <option value="sl-SI">Slovenščina</option>
            <option value="sr-SP">Српски / srpski</option>
            <option value="sv-SE">Svenska</option>
            <option value="th-TH">ไทย</option>
            <option value="tl-PH">Tagalog</option>
            <option value="tr-TR">Türkçe</option>
            <option value="uk-UA">Українська</option>
            <option value="ur-PK">اردو</option>
            <option value="vi-VN">Tiếng Việt</option>
            <option value="zh-CN">中文（简体）</option>
            <option value="zh-TW" selected="selected">中文（繁體）</option>
            <option value="zh-TM">正體中文（萌萌ㄉㄜ）(翻譯募集中...)</option>
            <option value="ka-KA">(๑˃̵ᴗ˂̵)و『( ·᷄ὢ·᷅ )...』</option>
          </select>
      
          <span class="input-group-addon" style="width:0px; padding-left:0px; padding-right:0px; border:none;"></span>
          <input id="otoko_change_interval" type="number" class="form-control" min="5" max="120" placeholder="min">
          <span class="input-group-addon" style="width:0px; padding-left:0px; padding-right:0px; border:none;"></span>
      
          <div class="input-group-btn">
              <button id="otoko_room_change" class="btn btn-default" type="button"
                                                                     data-delayed-toggle="collapse" data-target=""
                                                                                                    title="if auto change room">
                  <i id="" class="glyphicon 	glyphicon-plane"></i>
              </button>
          </div>
        </div>
      
        <div class="input-group">
      
      
          <input id="otoko_report_text" type="text" class="form-control" placeholder="REPORT TEXT">
      
          <span class="input-group-addon" style="width:0px; padding-left:0px; padding-right:0px; border:none;"></span>
          <input id="otoko_change_interval" type="number" class="form-control" min="5" max="120" placeholder="min">
          <span class="input-group-addon" style="width:0px; padding-left:0px; padding-right:0px; border:none;"></span>
          <div class="input-group-btn">
              <button id="otoko_set_text" class="btn btn-default" type="button"
                                                                     data-delayed-toggle="collapse" data-target=""
                                                                                                    title="set report text">
                  <i id="" class="glyphicon 	glyphicon-pencil"></i>
              </button>
          </div>
      </div><br>${intro}`
      }
      
      const ui_event = (config) => {
      
      }
      
      const event_action = (req, config) => {
        var type = req.type;
      }
      
      // game logic
      
      return {"ui": ui,
"ui_event": ui_event,
"event_action": event_action};
    })();
    Object.defineProperty(globalThis.__drrrModules, "module/otoko.js", {
      configurable: true,
      value: module,
    });
    return module;
  },
});

// module/p2p_chat.js
Object.defineProperty(globalThis.__drrrModules, "module/p2p_chat.js", {
  configurable: true,
  get() {
    const module = (() => {
      "use strict";
      var P2P_CHAT = "P2P_CHAT"
      
      var language = window.navigator.userLanguage || window.navigator.language;
      var intro = (language == 'zh-CN' || language == 'zh-TW') ?
        `歡迎使用點對點聊天模組。`:`Welcome to P2P CHAT module.`
      
      const ui = (config) => {
        return `
        <div class="input-group">
           <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
           <span class="input-group-addon form-control panel-footer text-center" title="call the peer">${intro}</span>
           <div class="input-group-btn">
            <button id="call_ui" class="btn btn-default" type="button" title="Launch UI">
              <i class="glyphicon glyphicon-phone-alt"></i>
            </button>
           </div>
        </div>
        <hr>
        <div class="row" style="height:100%">
          <div class="col-md-4">
            <div class="list-group" style="margin-bottom: 0px;">
              <div id='peer_list_container'></div>
            </div>
          </div>
        </div>`
      }
      
      var call_peer_btn = (args) =>
        `<button class="btn btn-default call-peer" type="submit"
               data="${args.data.id}"   title="call the peer user">
           <i class="glyphicon glyphicon-earphone"></i>
        </button>`
      
      function bind_call_peer(args){
        $(`.call-peer[data="${args.data.id}"]`).click(function(){
          chrome.tabs.create({
            url: chrome.runtime.getURL(`/peerjs/p2p-chat.html?uid=${args.data.selfID}&wait=${args.data.id}`)
          });
        });
      }
      
      const ui_event = (config) => {
        var data = {'peers': []};
        btn_funcbind[call_peer_btn] = bind_call_peer;
        getRoom((info) => {
          $('#call_ui').click(function(){
            var param = info.profile ? `?uid=${info.profile.id}` : '';
            chrome.tabs.create({
              url: chrome.runtime.getURL(`/peerjs/p2p-chat.html${param}`)
            });
          });
          if(info.room)
            info.room.users.forEach(u => {
              if(info.profile.name !== u.name)
                data.peers.push({
                  name: `${u.name}`,
                  id: u.id,
                  selfID: info.profile.id
                });
            })
          show_peer_list(data);
        }, (err) => {
          // alert("Cannot get room list");
          // https://alertifyjs.com/
        })
      }
      
      const event_action = (req, config) => {
        var type = req.type;
      }
      
      function show_peer_list(config){
        show_configlist(
          '#peer_list_container',
          'peers', ()=>{},
          [call_peer_btn],
          'EMPTY PEER USER LIST', {
            title: (c, e) => `call the peer`,
            content: (c, e) => `${e.name}`,
            data: (c, e) => ({id: e.id, selfID: e.selfID}),
            icon: 'glyphicon-list'
          }, config);
      }
      
      return {"ui": ui,
"ui_event": ui_event,
"event_action": event_action};
    })();
    Object.defineProperty(globalThis.__drrrModules, "module/p2p_chat.js", {
      configurable: true,
      value: module,
    });
    return module;
  },
});

// module/peer_call.js
Object.defineProperty(globalThis.__drrrModules, "module/peer_call.js", {
  configurable: true,
  get() {
    const module = (() => {
      "use strict";
      var PEER_CALL = "PEER_CALL"
      
      var language = window.navigator.userLanguage || window.navigator.language;
      var intro = (language == 'zh-CN' || language == 'zh-TW') ?
        `歡迎使用點對點通話模組。`:`Welcome to Peer Call module.`
      
      //Object.defineProperty(String.prototype, 'hashCode', {
      //  value: function() {
      //    var hash = 0, i, chr;
      //    for (i = 0; i < this.length; i++) {
      //      chr   = this.charCodeAt(i);
      //      hash  = ((hash << 5) - hash) + chr;
      //      hash |= 0; // Convert to 32bit integer
      //    }
      //    return hash;
      //  }
      //});
      
      const ui = (config) => {
        return `
        <div class="input-group">
           <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
           <span class="input-group-addon form-control panel-footer text-center">${intro}</span>
           <div class="input-group-btn">
            <button id="call_ui" class="btn btn-default" type="button" title="Launch UI">
              <i class="glyphicon glyphicon-phone-alt"></i>
            </button>
           </div>
        </div>
        <!--
        <div class="input-group">
          <div class="input-group-btn">
              <button id="trpg_host" class="btn btn-default" type="button" title="become host">
                  <i id="is_host" class="glyphicon glyphicon-user"></i>
              </button>
          </div>
      
          <span class="input-group-addon" style="width:0px; padding-left:0px; padding-right:0px; border:none;"></span>
      
          <input id="trpg_bg_url" type="text" class="form-control" placeholder="SCENE URL">
      
          <div class="input-group-btn">
              <button id="set_trpg_bg" class="btn btn-default" type="button"
                                                                     data-delayed-toggle="collapse" data-target=""
                                                                                                    title="set scene">
                  <i id="" class="glyphicon 	glyphicon-picture"></i>
              </button>
          </div>
        </div>
          -->
        <hr>
        <div class="row" style="height:100%">
          <div class="col-md-4">
            <div class="list-group" style="margin-bottom: 0px;">
              <div id='peer_list_container'></div>
            </div>
          </div>
        </div>`
      }
      
      var call_peer_btn = (args) =>
        `<button class="btn btn-default call-peer" type="submit"
               data="${args.data.id}"   title="call the peer user">
           <i class="glyphicon glyphicon-earphone"></i>
        </button>`
      
      function bind_call_peer(args){
        $(`.call-peer[data="${args.data.id}"]`).click(function(){
          chrome.tabs.create({
            url: chrome.runtime.getURL(`/peerjs/audio-chat.html?host=${args.data.selfID}&wait=${args.data.id}`)
          });
        });
      }
      
      const ui_event = (config) => {
        var data = {'peers': []};
        btn_funcbind[call_peer_btn] = bind_call_peer;
        getRoom((info) => {
          $('#call_ui').click(function(){
            var param = info.profile ? `?host=${info.profile.id}` : '';
            chrome.tabs.create({
              url: chrome.runtime.getURL(`/peerjs/audio-chat.html${param}`)
            });
          });
          if(info.room)
            info.room.users.forEach(u => {
              if(info.profile.name !== u.name)
                data.peers.push({
                  name: `${u.name}`,
                  id: u.id,
                  selfID: info.profile.id
                });
            })
          show_peer_list(data);
        }, (err) => {
          alert("Cannot get room list");
        })
      }
      
      const event_action = (req, config) => {
        var type = req.type;
        //var enemy = config[ENEMY];
        //var observe = config[OBSERVE];
        //if(!observe) observe = [];
        //if(!enemy) enemy = [];
        //if(type == event_join){
        //  if(enemy && enemy.includes(req.user)){
        //    setTimeout(()=> sendTab({ fn: ban_member, args: { user: req.user } }), 200);
        //  }
        //  else{
        //    if(!observe.includes(req.user)){
        //      observe.push(req.user);
        //      chrome.storage.local.set({ [OBSERVE]: observe });
        //      chrome.runtime.sendMessage({show_observe_list: true, config: config});
        //    }
        //  }
        //}
        //else if(type == event_leave && observe){
        //  if(observe.includes(req.user)){
        //    observe.splice(observe.indexOf(req.user), 1);
        //    enemy.push(req.user);
        //    chrome.storage.local.set({
        //      [OBSERVE]: observe,
        //      [ENEMY]: enemy
        //    });
        //    chrome.runtime.sendMessage({show_observe_list: true, show_peer_list: true, config: config});
        //  }
        //}
        //else{
        //  if(observe && observe.includes(req.user)){
        //    observe.splice(observe.indexOf(req.user), 1);
        //    chrome.storage.local.set({ [OBSERVE]: observe });
        //    chrome.runtime.sendMessage({show_observe_list: true, config: config});
        //  }
        //}
      }
      
      // module logic
      //function show_observe_list(config){
      //  show_configlist(
      //    '#observe_list_container',
      //    OBSERVE, ()=>{},
      //    [],
      //    'EMPTY OBERSERVATION LIST', {
      //      title: (c, name) => `${name} is in observation`,
      //      content: (c, name) => `${name}`,
      //      data: (c, name) => `${name}`,
      //      icon: 'glyphicon-list'
      //    }, config);
      //}
      
      function show_peer_list(config){
        show_configlist(
          '#peer_list_container',
          'peers', ()=>{},
          [call_peer_btn],
          'EMPTY PEER USER LIST', {
            title: (c, e) => `call the peer`,
            content: (c, e) => `${e.name}`,
            data: (c, e) => ({id: e.id, selfID: e.selfID}),
            icon: 'glyphicon-list'
          }, config);
      }
      
      return {"ui": ui,
"ui_event": ui_event,
"event_action": event_action};
    })();
    Object.defineProperty(globalThis.__drrrModules, "module/peer_call.js", {
      configurable: true,
      value: module,
    });
    return module;
  },
});

// module/pokemon.js
Object.defineProperty(globalThis.__drrrModules, "module/pokemon.js", {
  configurable: true,
  get() {
    const module = (() => {
      "use strict";
      
      const ui = () => {
        return `<p>WORK IN PROCESS</p>`
      }
      
      
      const ui_event = () => {
      
      
      }
      
      const event_action = () => {
      
      }
      
      return {"ui": ui,
"ui_event": ui_event,
"event_action": event_action};
    })();
    Object.defineProperty(globalThis.__drrrModules, "module/pokemon.js", {
      configurable: true,
      value: module,
    });
    return module;
  },
});

// module/room_chat.js
Object.defineProperty(globalThis.__drrrModules, "module/room_chat.js", {
  configurable: true,
  get() {
    const module = (() => {
      "use strict";
      var ROOM_CHAT = "ROOM_CHAT"
      
      var language = window.navigator.userLanguage || window.navigator.language;
      var intro = (language == 'zh-CN' || language == 'zh-TW') ?
        `歡迎使用房間聊天模組。`:`Welcome to Room Chat module.`
      
      const ui = (config) => {
        return `
        <div class="input-group">
      
          <!--
           <span id="unable_launch" title="You are not room owner" class="input-group-addon"><i class="glyphicon glyphicon-phone-alt"></i></span>
          -->
      
           <div id="able_launch" class="input-group-btn" >
             <button id="launch_room" class="btn btn-default" type="button" title="You are not room owner" disabled>
               <i class="glyphicon glyphicon-phone-alt"></i>
             </button>
           </div>
      
           <span class="input-group-addon form-control panel-footer text-center">${intro}</span>
      
           <div class="input-group-btn">
            <button id="join_room" class="btn btn-default" type="button" title="You are not in a room" disabled>
              <i class="glyphicon glyphicon-earphone"></i>
            </button>
           </div>
        </div>
      
        <!--
          <hr>
          <div class="row" style="height:100%">
            <div class="col-md-4">
              <div class="list-group" style="margin-bottom: 0px;">
                <div id='peer_list_container'></div>
              </div>
            </div>
          </div>
        -->`
      }
      
      var call_peer_btn = (args) =>
        `<button class="btn btn-default call-peer" type="submit"
               data="${args.data.id}"   title="call the peer user">
           <i class="glyphicon glyphicon-earphone"></i>
        </button>`
      
      const ui_event = (config) => {
        getRoom((info) => {
          console.log(info)
          if(info.room){
            if(info.room.host === info.profile.id){
              $('#launch_room')
                .attr('title', 'Launch Room Call')
                .attr('disabled', false)
                .click(function(){
                  chrome.tabs.create({
                    url: chrome.runtime.getURL(`/peerjs/room-chat.html?room=${encodeURIComponent(info.room.name)}&host=DRROOM${info.room.roomId}&uid=DRRR${info.profile.id}&name=${encodeURIComponent(info.profile.name)}`)
                  });
                });
            }
            $('#join_room')
              .attr('title', 'Join the Room')
              .attr('disabled', false)
              .click(function(){
              chrome.tabs.create({
                url: chrome.runtime.getURL(`/peerjs/room-chat.html?join=DRROOM${info.room.roomId}&uid=DRRR${info.profile.id}&name=${encodeURIComponent(info.profile.name)}`)
              });
            });
          }
        }, (err) => {
          // alert("Cannot get room list");
        })
      }
      
      const event_action = (req, config) => {
        var type = req.type;
      }
      
      return {"ui": ui,
"ui_event": ui_event,
"event_action": event_action};
    })();
    Object.defineProperty(globalThis.__drrrModules, "module/room_chat.js", {
      configurable: true,
      value: module,
    });
    return module;
  },
});

// module/room_guard.js
Object.defineProperty(globalThis.__drrrModules, "module/room_guard.js", {
  configurable: true,
  get() {
    const module = (() => {
      "use strict";
      var ROOM_GUARD = "ROOM_GUARD"
      var OBSERVE = "OBSERVE"
      var ENEMY = "ENEMY"
      
      var language = window.navigator.userLanguage || window.navigator.language;
      var count_alert = (language == 'zh-CN' || language == 'zh-TW') ? '倒數 5 秒，請回覆不然就踢' : 'reply me in 5 secs, or I\'ll kick you'
      
      var intro = (language == 'zh-CN' || language == 'zh-TW') ?
        `<p>歡迎使用房間守衛模組。<br>mode 0: 訪客如果進房後沒有任何動作，將在下次進房被 kick/ban。<br>mode 1: 時間內內沒說話，詢問是否 kick/ban。<br>mode 2: 時間內沒說話，倒數然後 kick/ban<br>mode 3: 時間內沒說話，直接 kick/ban</p>`:`<p>Welcome to room guard module.<br>mode 0: Uesr will be kick/ban next if leave room silently.<br>mode 1: Ask if kick/ban user if is silent in the period<br>mode 2: Count down then kick/ban if silent in the period<br>mode 3: Kick/ban the user if is silent in the period</p>`
      
      const ui = (config) => {
        return `
        ${intro}
        <!--
        <div class="input-group">
          <div class="input-group-btn">
              <button id="trpg_host" class="btn btn-default" type="button" title="become host">
                  <i id="is_host" class="glyphicon glyphicon-user"></i>
              </button>
          </div>
      
          <span class="input-group-addon" style="width:0px; padding-left:0px; padding-right:0px; border:none;"></span>
      
          <input id="trpg_bg_url" type="text" class="form-control" placeholder="SCENE URL">
      
          <div class="input-group-btn">
              <button id="set_trpg_bg" class="btn btn-default" type="button"
                                                                     data-delayed-toggle="collapse" data-target=""
                                                                                                    title="set scene">
                  <i id="" class="glyphicon 	glyphicon-picture"></i>
              </button>
          </div>
        </div>
          -->
        <select id="rgmode">
          <option value="0">mode 0</option>
          <option value="1">mode 1</option>
          <option value="2">mode 2</option>
          <option value="3">mode 3</option>
        </select>
        <select id="rgkmode">
          <option value="0">kick</option>
          <option value="1">ban</option>
          <option value="2">report</option>
        </select>
        <select id="rgktime">
          <option value="10000">10 secs</option>
          <option value="30000">30 secs</option>
          <option value="60000">1 min</option>
          <option value="120000">2 min</option>
          <option value="240000">4 min</option>
          <option value="480000">8 min</option>
          <option value="960000">12 min</option>
          <option value="1920000">24 min</option>
        </select>
        <hr>
        <div class="row" style="height:100%">
          <div class="col-md-4">
            <div class="list-group" style="margin-bottom: 0px;">
              <div id='observe_list_container'></div>
              <div id='enemy_list_container'></div>
            </div>
          </div>
        </div>`
      }
      
      var del_enemy_btn = (args) =>
        `<button class="btn btn-default del-enemy" type="submit"
               data="${args.data}"   title="remove the user from enemy list">
           <i class="glyphicon glyphicon-remove"></i>
        </button>`
      
      function bind_del_enemy(args){
        $(`.del-enemy[data="${args.data}"]`).click(function(){
          chrome.storage.local.get([ENEMY], (config) =>{
            var enemy = config[ENEMY]
            enemy.splice(enemy.indexOf($(this).attr('data')), 1);
            chrome.storage.local.set({ [ENEMY]: enemy });
            show_enemy_list(config);
          });
        });
      }
      
      
      const ui_event = (config) => {
      
        var mode = config['#rgmode'] || 0;
        var kmode = config['#rgkmode'] || 0;
        var ktime = config['#rgktime'] || 120000;
        $('#rgmode').val(mode);
        $('#rgmode').on('change', function() {
          chrome.storage.local.set({'#rgmode': this.value});
          mode = this.value;
        });
        $('#rgkmode').val(kmode);
        $('#rgkmode').on('change', function() {
          chrome.storage.local.set({'#rgkmode': this.value});
          kmode = this.value;
        });
        $('#rgktime').val(ktime);
        $('#rgktime').on('change', function() {
          chrome.storage.local.set({'#rgktime': this.value});
          ktime = this.value;
        });
      
        btn_funcbind[del_enemy_btn] = bind_del_enemy;
        show_observe_list(config);
        show_enemy_list(config);
      
        chrome.runtime.onMessage.addListener((req, sender, callback) => {
          if(req){
            if(req.show_observe_list) show_observe_list(req.config);
            if(req.show_enemy_list) show_enemy_list(req.config);
          }
          if(callback) callback();
        });
      }
      
      const kmodes = [kick_member, ban_member, ban_report_member];
      
      const event_action = (req, config) => {
      
        var type = req.type;
        var enemy = config[ENEMY] || [];
        var observe = config[OBSERVE] || [];
        var mode = config['#rgmode'] || 0;
        var kmode = config['#rgkmode'] || 0;
        var ktime = config['#rgktime'] || 120000;
      
        if(!req.host){
          if(observe.length || enemy.length)
            chrome.storage.local.set({ [ENEMY]: [], [OBSERVE]: [] });
          return;
        }
      
        if(type == event_join){
          if(enemy && enemy.includes(req.user) && mode == 0){
            setTimeout(()=> sendTab({ fn: kmodes[kmode], args: { user: req.user } }), 200);
          }
          else{
            sendTab({fn: set_clock, args: {ms: Number(ktime), from: ROOM_GUARD, user: req.user}});
            if(!observe.includes(req.user)){
              observe.push(req.user);
              chrome.storage.local.set({ [OBSERVE]: observe });
              chrome.runtime.sendMessage({show_observe_list: true, config: config});
            }
          }
        }
        else if(type == event_leave && observe){
          if(observe.includes(req.user)){
            observe.splice(observe.indexOf(req.user), 1);
            enemy.push(req.user);
            chrome.storage.local.set({
              [OBSERVE]: observe,
              [ENEMY]: enemy
            });
            chrome.runtime.sendMessage({show_observe_list: true, show_enemy_list: true, config: config});
          }
        }
        else if(type == event_clock){
          if(req.args.from == ROOM_GUARD &&
            (observe.includes(req.args.user) || req.args.action)){
            if(mode == 1){
              sendTab({fn: show_confirm, args: {text: `Do you want to kick ${req.args.user}?`}}, undefined, function(yn){
                if(yn){
                  setTimeout(()=> sendTab({ fn: kmodes[kmode], args: { user: req.args.user } }), 200);
                }
              });
            }
            else if(mode == 2){
              if(req.args.action === undefined){
                sendTab({
                  fn: dm_member,
                  args: { msg: `@${req.args.user} ${count_alert}`,
                          user: req.args.user} });
                setTimeout(()=>sendTab({
                  fn: set_clock,
                  args: {ms: 5000, from: ROOM_GUARD, user: req.args.user, action: "del"}}), 100);
              }
              else if(req.args.action == "del"){
                setTimeout(()=> sendTab({
                  fn: kmodes[kmode], args: { user: req.args.user } }), 200);
              }
            }
            else if(mode == 3){
              setTimeout(()=> sendTab({ fn: kmodes[kmode], args: { user: req.args.user } }), 200);
            }
          }
        }
        else if([event_kick, event_ban].includes(type)){
          if(observe.includes(req.user)){
            observe.splice(observe.indexOf(req.user), 1);
            chrome.storage.local.set({ [OBSERVE]: observe });
          }
        }
        else{
          if(observe && observe.includes(req.user)){
            observe.splice(observe.indexOf(req.user), 1);
            chrome.storage.local.set({ [OBSERVE]: observe });
            chrome.runtime.sendMessage({show_observe_list: true, config: config});
          }
        }
      }
      
      // module logic
      function show_observe_list(config){
        show_configlist(
          '#observe_list_container',
          OBSERVE, ()=>{},
          [],
          'EMPTY OBERSERVATION LIST', {
            title: (c, name) => `${name} is in observation`,
            content: (c, name) => `${name}`,
            data: (c, name) => `${name}`,
            icon: 'glyphicon-list'
          }, config);
      }
      
      function show_enemy_list(config){
        show_configlist(
          '#enemy_list_container',
          ENEMY, ()=>{},
          [del_enemy_btn],
          'EMPTY ENEMY LIST', {
            title: (c, name) => `delete ${name} from enemy list`,
            content: (c, name) => `${name}`,
            data: (c, name) => `${name}`,
            icon: 'glyphicon-list'
          }, config);
      }
      
      function sleep(milliseconds) {
        var start = new Date().getTime();
        for (var i = 0; i < 1e7; i++) {
          if ((new Date().getTime() - start) > milliseconds){
            break;
          }
        }
      }
      
      return {"ui": ui,
"ui_event": ui_event,
"event_action": event_action};
    })();
    Object.defineProperty(globalThis.__drrrModules, "module/room_guard.js", {
      configurable: true,
      value: module,
    });
    return module;
  },
});

// module/trpg.js
Object.defineProperty(globalThis.__drrrModules, "module/trpg.js", {
  configurable: true,
  get() {
    const module = (() => {
      "use strict";
      var GAME_TRPG = "GAME_TRPG"
      
      var language = window.navigator.userLanguage || window.navigator.language;
      var intro = (language == 'zh-CN' || language == 'zh-TW') ?
        `<p>歡迎使用 TRPG 遊戲模組<br>發送 <code>2D10</code> 讓 host 幫你搖兩個骰子（1-10）</p>`:`<p>Welcome to TRPG game module<br>send <code>2D10</code> let host roll 2 dices(1-10) for you</p>`
      
      const ui = (config) => {
        return `
      <div class="input-group">
          <div class="input-group-btn">
              <button id="trpg_host" class="btn btn-default" type="button" title="become host">
                  <i id="is_host" class="glyphicon glyphicon-user"></i>
              </button>
          </div>
      
          <span class="input-group-addon" style="width:0px; padding-left:0px; padding-right:0px; border:none;"></span>
      
          <input id="trpg_bg_url" type="text" class="form-control" placeholder="SCENE URL">
      
          <div class="input-group-btn">
              <button id="set_trpg_bg" class="btn btn-default" type="button"
                                                                     data-delayed-toggle="collapse" data-target=""
                                                                                                    title="set scene">
                  <i id="" class="glyphicon 	glyphicon-picture"></i>
              </button>
          </div>
      </div><br>${intro}`
      }
      
      const ui_event = (config) => {
        $('#set_trpg_bg').click(()=>{
          sendTab({
            fn: publish_message,
            args: { msg: '[TRPG SCENE]', url: $('#trpg_bg_url').val()}
          });
        });
      
        host(config['trpg_is_host']);
      
        $('#trpg_host').click(()=>{
          if($('#is_host').hasClass('glyphicon-user')){
            host(true, true);
            setTimeout(()=>sendTab({ fn: publish_message, args: { msg: '[TRPG HOST]'} }), 1000);
          }
          else{
            host(false, true);
            setTimeout(()=>sendTab({ fn: publish_message, args: { msg: '[TRPG PLAYER]'} }), 1000);
          }
        });
      }
      
      const event_action = (req, config) => {
        var type = req.type;
        if(type == event_msg || type == event_me){
          if(req.text.match(/^\d+[dD]\d+$/)){
            setTimeout(()=>{ if(config['trpg_is_host']) sendTab({ fn: publish_message, args: { msg: dice(req.text) } }) }, 800);
          }
          else if(req.text == '[TRPG SCENE]'){
            setTimeout(()=> sendTab({ fn: change_bg_img_url, args: { url: req.url } }), 200);
          }
          else if(req.text == '[TRPG HOST]'){
            setTimeout(()=> getProfile((p)=>{
              if(p.name != req.user){
                host(false, true);
              }
            }), 500);
          }
        }
        else if(type == event_dm){
          if(req.text.match(/^\d+[dD]\d+$/)){
            setTimeout(()=>{
              if(config['trpg_is_host'])
                sendTab({ fn: dm_member, args: { msg: dice(req.text), user: req.user } })
            }, 800);
          }
        }
      }
      
      // game logic
      
      function host(bool, set){
        if(bool){
          $('#is_host').removeClass('glyphicon-user')
          $('#is_host').addClass('glyphicon-bullhorn')
          $('#trpg_host').attr('title', 'become player');
        }
        else{
          $('#is_host').removeClass('glyphicon-bullhorn')
          $('#is_host').addClass('glyphicon-user')
          $('#trpg_host').attr('title', 'become host');
        }
        if(set){ chrome.storage.local.set({ 'trpg_is_host': bool }); }
      }
      
      function dice(text){
        var match = (/^(\d+)[dD](\d+)$/g).exec(text)
        if(!match) return "wrong format, use [1-100]d[digits]"
        var ins = Number(match[1]);
        if(ins > 0 && ins <= 100){
          return [...Array(ins)].map((_, i) => String(Math.floor(Math.random()*match[2])+1)).join(' ');
        }
        else return "number of dice should between 1 to 100";
      }
      
      //function new_note(){
      //  $.ajax({
      //    type: "GET",
      //    url: 'https://hackmd.io',
      //    dataType: 'html',
      //    success: function(data){
      //      var nodes = $(data);
      //      $.ajax({
      //        type: "POST",
      //        url: 'https://hackmd.io/template/template-Try-it?redirect=true',
      //        data: {'_csrf': nodes.find('input[name="_csrf"]').val()},
      //        dataType: 'html',
      //        headers: {
      //          'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
      //          'accept-encoding': 'gzip, deflate, br',
      //          'accept-language': 'zh-TW,zh;q=0.9,zh-CN;q=0.8,en;q=0.7',
      //          'cache-control': 'max-age=0',
      //          'content-length': '42',
      //          'content-type': 'application/x-www-form-urlencoded',
      //          'origin': 'https://hackmd.io',
      //          'referer': 'https://hackmd.io/',
      //          'sec-fetch-dest': 'document',
      //          'sec-fetch-mode': 'navigate',
      //          'sec-fetch-site': 'same-origin',
      //          'sec-fetch-user': '?1',
      //          'upgrade-insecure-requests': '1',
      //          'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36',
      //        },
      //        success: function(data){
      //          alert(data);
      //        },
      //        error: function(data){
      //          console.log(data);
      //        }
      //      });
      //    },
      //    error: function(data){
      //      console.log(data);
      //    }
      //  });
      //}
      
      /*
      ?BGM系統 - 輸入.mp3的網址可以直接撥放(GM用)
      v對話(打字)系統 - 可以語音跑團搭配使用，單純用文字跑團也可以
      ○角色系統 - 玩家可以輸入角色數值，方便增減
      v線上擲骰系統 - 內建的線上擲骰系統
      ○筆記系統 - 分成共用和私人筆記
      v背景圖系統 - 可以輸入圖片網址 / 上傳圖片，在頁面裡可以顯示當背景圖(GM用)
      v錄影系統 - 可以側錄進行的過程 - TG bot
      ○地圖系統 - 有點類似RPG製做大師，可以製作地圖
      ○方塊系統 - 可以建立棋子、角色方塊、指示方塊
      ○立繪系統 - 可以將導入圖片顯示在角色棋子上
      ○卡片系統 - 各式TRPG卡片，也可以自訂卡片
      */
      
      return {"ui": ui,
"ui_event": ui_event,
"event_action": event_action};
    })();
    Object.defineProperty(globalThis.__drrrModules, "module/trpg.js", {
      configurable: true,
      value: module,
    });
    return module;
  },
});

// setting/plugin/chatlog.js
Object.defineProperty(globalThis.__drrrModules, "setting/plugin/chatlog.js", {
  configurable: true,
  get() {
    const module = (() => {
      "use strict";
      function log2mkd(type, e){
        //type, user, text, url
        console.log('log data', e);
        if(type === event_msg)
          return `*${e.user}*: ${e.text}${e.url? ` [URL](${e.url})`: ''}`
        if(type === event_me)
          return `_${e.user}_: ${e.text}${e.url? ` [URL](${e.url})`: ''}`
        if(type === event_dm)
          return `${e.user}: ${e.text}${e.url? ` [URL](${e.url})`: ''}`
        if(type === event_join)
          return `${e.user} join the room`
        if(type === event_leave)
          return `${e.user} leave the room`
        if(type === event_newhost)
          return `${e.user} become the room owner`
      }
      
      const ts = [event_msg, event_me, event_dm, event_join, event_leave, event_newhost];
      const event_action = (req, config) => {
        const MODULE_NAME = "ChatLog";
        const MODULE_SETTING = sid(MODULE_NAME);
        if(ts.indexOf(req.type) >= 0){
          //alert(log2mkd(event_msg, req));
          // chrome.storage.local.get(MODULE_SETTING, (config)=>{
            if(!config[MODULE_SETTING])
              config[MODULE_SETTING] = [];
            config[MODULE_SETTING].push([req.type, req.user, req.text, req.url]);
            chrome.storage.local.set({
              [MODULE_SETTING]: config[MODULE_SETTING]
            }, function(){
              if(chrome.runtime.lastError)
                $.notify("ChatLog is full!", 'error');
            });
          // });
        }
      };
      
      return {"event_action": event_action};
    })();
    Object.defineProperty(globalThis.__drrrModules, "setting/plugin/chatlog.js", {
      configurable: true,
      value: module,
    });
    return module;
  },
});

// setting/plugin/eventaction.js
Object.defineProperty(globalThis.__drrrModules, "setting/plugin/eventaction.js", {
  configurable: true,
  get() {
    const module = (() => {
      "use strict";
      
      const event_action = (req, config, sender, pre_event_action) => {
        const MODULE_NAME = EVENTACT;
        const MODULE_SETTING = sid(MODULE_NAME);
        var type = req.type;
        // chrome.storage.local.get(MODULE_SETTING, (config)=>{
          if(!config[MODULE_SETTING]) return;
          event_events.forEach(et => {
            if(et === req.type) pre_event_action(et, config, req)
          })
        // });
      };
      
      return {"event_action": event_action};
    })();
    Object.defineProperty(globalThis.__drrrModules, "setting/plugin/eventaction.js", {
      configurable: true,
      value: module,
    });
    return module;
  },
});

// setting/plugin/hashtag.js
Object.defineProperty(globalThis.__drrrModules, "setting/plugin/hashtag.js", {
  configurable: true,
  get() {
    const module = (() => {
      "use strict";
      
      const event_action = (req, config) => {
        const MODULE_NAME = "Hashtag";
        const MODULE_SETTING = sid(MODULE_NAME);
        var type = req.type;
        if(type == event_msg){
          var reg = /#[\w\p{Script=Hiragana}\p{Script=Katakana}\p{Script=Han}\u3131-\uD79D]+/g, result;
          var pure = req.text.replace(reg, '').trim();
          if(!pure.length) return;
          while((result = reg.exec(req.text)) !== null) {
            // chrome.storage.local.get(MODULE_SETTING,
            ((r)=>
              // (config)=>
              {
                if(!config[MODULE_SETTING])
                  config[MODULE_SETTING] = {};
                var list = config[MODULE_SETTING][r] || [];
                list.push(pure);
                config[MODULE_SETTING][r] = list;
                chrome.storage.local.set({
                  [MODULE_SETTING]: config[MODULE_SETTING]
                }, function(){
                  if(chrome.runtime.lastError)
                    $.notify("HashTag is full!", 'error');
                });
              }
            )(result)
            // );
          }
        }
      };
      
      return {"event_action": event_action};
    })();
    Object.defineProperty(globalThis.__drrrModules, "setting/plugin/hashtag.js", {
      configurable: true,
      value: module,
    });
    return module;
  },
});
